### ISSUE TITLE
AttributeError: Ui instance has no attribute 'build_login'

### ISSUE THREAD

**Issue by riaqn** [darknessomi/musicbox#102]
```
Traceback (most recent call last):
  File "/home/riaqn/.local/bin/musicbox", line 9, in <module>
    load_entry_point('musicbox==0.1.2.4', 'console_scripts', 'musicbox')()
  File "/home/riaqn/.local/lib64/python2.7/site-packages/src/__init__.py", line 11, in start
    Menu().start()
  File "/home/riaqn/.local/lib64/python2.7/site-packages/src/menu.py", line 160, in start
    self.dispatch_enter(idx)
  File "/home/riaqn/.local/lib64/python2.7/site-packages/src/menu.py", line 306, in dispatch_enter
    self.choice_channel(idx)
  File "/home/riaqn/.local/lib64/python2.7/site-packages/src/menu.py", line 438, in choice_channel
    data = self.ui.build_login()
AttributeError: Ui instance has no attribute 'build_login'
```

How to reproduce:
1. open musicbox
2. Press mutiple `J` to move to `4. 我的歌单`
3. Press Enter

this problem exists on both python2.7 and python3.4.

**Comment by Catofes** [comment]
1. This app didn't work under python3. Please use python2.7
2. Try to update the app.  

Seems your version is 0.1.2.4. Now the newest one is 0.1.7.1

**Comment by riaqn** [comment]
@Catofes 
Yes I see. i use `pip install musicbox` to install the program. should use `pip install NetEase-MusicBox`.
Now it works.
