### ISSUE TITLE
用什么命令更新？

### ISSUE THREAD

**Issue by VDerGoW** [darknessomi/musicbox#150]
Ubuntu上提示可以更新了，该怎么更新呢？

**Comment by darknessomi** [comment]
``` sudo pip install --upgrade NetEase-MusicBox ```

**Comment by VDerGoW** [comment]
谢谢

**Comment by caisan** [comment]
我在10.9的系统上更新出现错误了。
```Traceback (most recent call last):
  File "/usr/local/bin/musicbox", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2603, in <module>
    working_set.require(__requires__)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 666, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 565, in resolve
    raise DistributionNotFound(req)  # XXX put more info here
pkg_resources.DistributionNotFound: BeautifulSoup4
```
