### ISSUE TITLE
不能登录

### ISSUE THREAD

**Issue by lain8023** [darknessomi/musicbox#195]
使用手机号和邮箱都不能登录，特意改了个简单的密码也没有用

**Comment by 11hwu2** [comment]
我也发现输入正确的手机号与密码不能登陆，安装使用的版本是NetEase-MusicBox-0.2.0.6，系统是ubuntu14.04。

**Comment by jiangming1399** [comment]
同

**Comment by Catofes** [comment]
确认网页版能不能登陆，有时候尝试次数太多会被封掉，改天再登陆就好了

**Comment by 11hwu2** [comment]
手机客户端（多个设备同时）和网页版都能正常登陆。

**Comment by gloxec** [comment]
同样无法登录，，，真是抓狂啊

**Comment by sjzlyl406** [comment]
打开网易云音乐网页版等陆到个人主页==>从链接上复制id==>在终端打开～/.netease-musicbox/database.json找到usrid一项==>将id粘贴到这里。就能正常登陆了。

follow me at [github](https://github.com/sjzlyl406)。

**Comment by darknessomi** [comment]
@sjzlyl406 这样的话，只能获取到歌单，但是并没有用户 Cookie，FM 和 推荐不能正常使用。
我猜，难道是 Ubuntu 的加密出了问题。。。

**Comment by jinxingxing** [comment]
https://gist.githubusercontent.com/jinxingxing/b990267b7903a20decea/raw/d138d7b802fcc0b23a386c5f60be4044eeed2c85/musicbox_login.py

提供一个临时的解决办法

**Comment by owensss** [comment]
同不能登录

报的是这个错：

```
2016-05-06 10:28:21,108 - DEBUG - menu:716: Re Login.
2016-05-06 10:28:29,854 - ERROR - api:261: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)
2016-05-06 10:28:40,023 - ERROR - api:246: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)
```

**Comment by lonicerae** [comment]
一个暂时解决的补丁如下：
```
$ cat /tmp/musicbox-login.path 
--- /usr/lib/python2.7/site-packages/NEMbox/api.py.orig	2016-08-26 13:27:46.793078233 +0800
+++ /usr/lib/python2.7/site-packages/NEMbox/api.py	2016-08-26 13:28:20.526179092 +0800
@@ -161,6 +161,7 @@
         self.cookies = {'appver': '1.5.2'}
         self.playlist_class_dict = {}
         self.session = requests.Session()
+        self.session.verify = False
         self.storage = Storage()
         self.session.cookies = LWPCookieJar(self.storage.cookie_path)
         try:
```
这里把网易返回来的证书无论是否verified的都接受，就可以解决登陆的问题。

**Comment by lousiyu** [comment]
你好，我每次登录就报错
__Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/__init__.py", line 27, in start
    nembox_menu.start_fork(version)
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/menu.py", line 177, in start_fork
    Menu().start()
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/menu.py", line 338, in start
    self.dispatch_enter(idx)
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/menu.py", line 613, in dispatch_enter
    self.choice_channel(idx)
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/menu.py", line 843, in choice_channel
    self.userid)
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/menu.py", line 777, in request_api
    data = self.ui.build_login()
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/ui.py", line 507, in build_login
    login_info = self.netease.login(local_account, local_password)
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/api.py", line 258, in login
    return self.httpRequest('Login_POST', action, data)
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/api.py", line 213, in httpRequest
    method, action, query, urlencoded, callback, timeout))
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/api.py", line 240, in rawHttpRequest
    self.session.cookies.save()
  File "/usr/lib/python2.7/_LWPCookieJar.py", line 89, in save
    f.write(self.as_lwp_str(ignore_discard, ignore_expires))
  File "/usr/lib/python2.7/_LWPCookieJar.py", line 75, in as_lwp_str
    r.append("Set-Cookie3: %s" % lwp_cookie_str(cookie))
  File "/usr/lib/python2.7/_LWPCookieJar.py", line 35, in lwp_cookie_str
    time2isoz(float(cookie.expires))))
  File "/usr/lib/python2.7/cookielib.py", line 99, in time2isoz
    year, mon, mday, hour, min, sec = time.gmtime(t)[:6]
ValueError: timestamp out of range for platform time_t
看起来好像是python的问题，求教，谢谢

**Comment by kigawas** [comment]
@lousiyu
这是32位Python的bug（时间戳超过32位整数了），建议使用64位Python。
一个workaround是在64位机器上登录然后把cookie拷贝到对应位置
