### ISSUE TITLE
点击我的歌单报错

### ISSUE THREAD

**Issue by wweir** [darknessomi/musicbox#204]
界面信息：
Traceback (most recent call last):
File "/usr/local/bin/musicbox", line 9, in <module>
load_entry_point('musicbox==0.1.2.4', 'console_scripts', 'musicbox')()
File "/usr/local/lib/python2.7/dist-packages/src/__init__.py", line 11, in start
Menu().start()
File "/usr/local/lib/python2.7/dist-packages/src/menu.py", line 160, in start
self.dispatch_enter(idx)
File "/usr/local/lib/python2.7/dist-packages/src/menu.py", line 306, in dispatch_enter
self.choice_channel(idx)
File "/usr/local/lib/python2.7/dist-packages/src/menu.py", line 438, in choice_channel
data = self.ui.build_login()
AttributeError: Ui instance has no attribute 'build_login'
musicbox.log中只有两排#号

**Comment by wweir** [comment]
安错版本，pip2 里的 musicbox 不能用，必须照着README中的来
