### ISSUE TITLE
大家的每日推荐能用吗？

### ISSUE THREAD

**Issue by VDerGoW** [darknessomi/musicbox#206]
上次安装后我的每日推荐功能就用不了了，刚才更新了一下还是不能用，以前没问题的。
进入每日推荐之后会显示`这里什么都没有 - , -`

**Comment by xiaoming200990** [comment]
现在根本就登陆不了。进入每日推荐需要登陆，输入账户密码后提示进入不了，选择稍后再试就会报错并退出。
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/__init__.py", line 18, in start
    nembox_menu.start_fork(version)
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/menu.py", line 152, in start_fork
    Menu().start()
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/menu.py", line 496, in start
    self.ui.build_menu(self.datatype, self.title, self.datalist, self.offset, self.index, self.step, self.START)
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/ui.py", line 212, in build_menu
    'artist'] + '  < ' + datalist[i]['album_name'] + ' >')
TypeError: string indices must be integers, not str

**Comment by lianxiangru** [comment]
不能使用

**Comment by MichaelVipub** [comment]
不能用

**Comment by Catofes** [comment]
应该是API的问题。

**Comment by lianxiangru** [comment]
可以用了
关issue吧
