### ISSUE TITLE
选择我的歌单的时候异常退出，屏幕也跟着变乱了

### ISSUE THREAD

**Issue by MichaelVipub** [darknessomi/musicbox#211]
选择我的歌单以后屏幕如下：
                   享受高品质音乐，loading...Traceback (most recent call last):
                                                                                 File "/usr/bin/musicbox", line 9, in <module>
                   0. 排行榜                                                                                                      load_entry_point('musicbox==0.1.2.4', 'console_scripts', 'musicbox')()
                   2. 新碟上架                      File "/usr/lib/python2.7/site-packages/src/__init__.py", line 11, in start
                   3. 精选歌单                                                                                                    Menu().start()
                -> 4. 我的歌单                                                                                                                    File "/usr/lib/python2.7/site-packages/src/menu.py", line 133, in start
                   6. 打碟                                             self.dispatch_enter(idx)
                   7. 收藏                                                                       File "/usr/lib/python2.7/site-packages/src/menu.py", line 306, in dispatch_enter
                   9. 帮助     self.choice_channel(idx)
                                                         File "/usr/lib/python2.7/site-packages/src/menu.py", line 438, in choice_channel
                                                                                                                                             data = self.ui.build_login()
                   AttributeError: Ui instance has no attribute 'build_login'
                                                                             [michael@localhost .netease-musicbox]$

**Comment by MichaelVipub** [comment]
看到相关的问题了。
pip install NetEase-MusicBox.
