### ISSUE TITLE
Mac 10.11.2 为何提示找到不 NEMbox 模块？

### ISSUE THREAD

**Issue by bao3** [darknessomi/musicbox#222]
安装 pip 是使用 brew 中 python自带的，因此不需要 sudo，结果顺利安装了 music box后，执行就会得到如下提示
```

➜  bin git:(master) musicbox
Traceback (most recent call last):
  File "/usr/local/bin/musicbox", line 7, in <module>
    from NEMbox import start
ImportError: No module named NEMbox
➜  bin git:(master) which -a musicbox
/usr/local/bin/musicbox
➜  bin git:(master) python print sys.path
/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
➜  bin git:(master)

```
然后我发现，这个 NEMBox竟然是有的，只是路径有点怪

```
➜  bin git:(master) cd /usr/local/lib/python2.7/site-packages/Users/bao3/Library/Python/2.7/lib/python/site-packages/NEMbox/
➜  NEMbox git:(master) ls
__init__.py      api.pyc          config.py        const.pyc        menu.py          player.pyc       singleton.py     storage.pyc      ui.py
__init__.pyc     cache.py         config.pyc       logger.py        menu.pyc         scrollstring.py  singleton.pyc    terminalsize.py  ui.pyc
api.py           cache.pyc        const.py         logger.pyc       player.py        scrollstring.pyc storage.py       terminalsize.pyc
➜  NEMbox git:(master)
```

看起来是存在的，只是好像 musicbox 找不到啊。这个可怎么办？

**Comment by bao3** [comment]
补充一下：
我现在使用 Mac自带的 python也是一样，同样的错误

```
➜  ~  sudo proxychains4 pip install NetEase-MusicBox
[proxychains] config file found: /usr/local/Cellar/proxychains-ng/4.10/etc/proxychains.conf
[proxychains] preloading /usr/local/Cellar/proxychains-ng/4.10/lib/libproxychains4.dylib
The directory '/Users/bao3/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/bao3/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting NetEase-MusicBox
Collecting pycrypto (from NetEase-MusicBox)
  Downloading pycrypto-2.6.1.tar.gz (446kB)
    100% |████████████████████████████████| 446kB 96kB/s
Collecting BeautifulSoup4 (from NetEase-MusicBox)
  Downloading beautifulsoup4-4.4.1-py2-none-any.whl (81kB)
    100% |████████████████████████████████| 81kB 69kB/s
Collecting requests (from NetEase-MusicBox)
  Downloading requests-2.9.1-py2.py3-none-any.whl (501kB)
    100% |████████████████████████████████| 503kB 65kB/s
Installing collected packages: pycrypto, BeautifulSoup4, requests, NetEase-MusicBox
  Running setup.py install for pycrypto
Successfully installed BeautifulSoup4-4.4.1 NetEase-MusicBox-0.2.0.8 pycrypto-2.6.1 requests-2.9.1
➜  ~
➜  ~
➜  ~  rehash
➜  ~  musicbox
Traceback (most recent call last):
  File "/usr/local/bin/musicbox", line 7, in <module>
    from NEMbox import start
ImportError: No module named NEMbox

➜  ~  which python
/usr/bin/python

```

PIP 的安装是直接使用 sudo 来安装的：

```
➜  Versions  sudo python easy_install pip
python: can't open file 'easy_install': [Errno 2] No such file or directory
➜  Versions  sudo proxychains4 easy_install pip
[proxychains] config file found: /usr/local/Cellar/proxychains-ng/4.10/etc/proxychains.conf
[proxychains] preloading /usr/local/Cellar/proxychains-ng/4.10/lib/libproxychains4.dylib
Searching for pip
Reading https://pypi.python.org/simple/pip/
Best match: pip 7.1.2
Downloading https://pypi.python.org/packages/source/p/pip/pip-7.1.2.tar.gz#md5=3823d2343d9f3aaab21cf9c917710196
Processing pip-7.1.2.tar.gz
Writing /tmp/easy_install-Axb6SZ/pip-7.1.2/setup.cfg
Running pip-7.1.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-Axb6SZ/pip-7.1.2/egg-dist-tmp-nY_jDh
warning: no previously-included files found matching '.coveragerc'
warning: no previously-included files found matching '.mailmap'
warning: no previously-included files found matching '.travis.yml'
warning: no previously-included files found matching 'pip/_vendor/Makefile'
warning: no previously-included files found matching 'tox.ini'
warning: no previously-included files found matching 'dev-requirements.txt'
no previously-included directories found matching '.travis'
no previously-included directories found matching 'docs/_build'
no previously-included directories found matching 'contrib'
no previously-included directories found matching 'tasks'
no previously-included directories found matching 'tests'
Adding pip 7.1.2 to easy-install.pth file
Installing pip script to /usr/local/bin
Installing pip2.7 script to /usr/local/bin
Installing pip2 script to /usr/local/bin

Installed /Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg
Processing dependencies for pip
Finished processing dependencies for pip
```

所以现在我有点迷茫，不知道问题在哪里却一起提示少那个模块。同时我也关闭了 OSX 的 SIP 机制。请帮我看一下，我应该如何解决？

**Comment by darknessomi** [comment]
你好，我曾经也因为 OSX 多个 Python 版本的问题而烦恼过
首先你要确定你想要使用哪一个 Python
```
➜  ~  where python
/usr/local/bin/python
/usr/bin/python
```
正常情况下，通过 brew 安装 Python 之后，系统会共存两个 Python，而且有可能会共存两个 pip。
这是 brew 安装 Python 后使用 pip 安装 musicbox 的真实路径 ``` /usr/local/lib/python2.7/site-packages/NEMbox ```

个人推荐放弃系统自带 Python 版本，全部使用 brew 版本，自带 Python 版本的 pip 也建议一起删除。

**Comment by bao3** [comment]
@darknessomi  THX,果然解决了，确实是多个 python 引起，加上之前使用 sudo 安装了 music box 结果普通用户下又可以安装一次，导致了问题重叠，全部删除后恢复

*Thanks*
