### ISSUE TITLE
出现跳歌现象

### ISSUE THREAD

**Issue by Bokjan** [darknessomi/musicbox#232]
有许多歌曲会自动跳掉，还有连跳多首的情况，系统通知duang的一下就炸了。

相关错误如下。
~~~
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/__init__.py", line 18, in start
    nembox_menu.start_fork(version)
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/menu.py", line 152, in start_fork
    Menu().alert(version)
    Menu().start()
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/menu.py", line 195, in start
    key = self.screen.getch()
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/menu.py", line 129, in send_kill
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/menu.py", line 132, in alert
    sys.exit()
    latest = Menu().check_version()
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/menu.py", line 143, in check_version
SystemExit
    tree = ET.ElementTree(ET.fromstring(str(self.netease.get_version())))
  File "<string>", line 124, in XML
ParseError: syntax error: line 1, column 0
~~~
系统：Linux Deepin 2015.01 。

**Comment by hlx98007** [comment]
seconded. 有这个现象

**Comment by YaozhongZhang** [comment]
同样现象，有部分歌曲无法播放，每次都会跳过。

**Comment by amitbha** [comment]
看着是 netease.get_version() 出错了，和跳歌会有关系？
