### ISSUE TITLE
[bug]TypeError:object of type 'bool' has no len()

### ISSUE THREAD

**Issue by sjzlyl406** [darknessomi/musicbox#236]
点击每日推荐时，弹出下面错误：

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/__init__.py", line 18, in start
    nembox_menu.start_fork(version)
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/menu.py", line 152, in start_fork
    Menu().start()
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/menu.py", line 286, in start
    self.dispatch_enter(idx)
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/menu.py", line 514, in dispatch_enter
    self.choice_channel(idx)
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/menu.py", line 739, in choice_channel
    self.datalist = self.netease.dig_info(myplaylist, self.datatype)
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/api.py", line 521, in dig_info
    for i in range(0, len(data)):
TypeError: object of type 'bool' has no len()

**Comment by Catofes** [comment]
请更新
