### ISSUE TITLE
播放的时候报  “unknown option -a "   “io error，断开的管道“

### ISSUE THREAD

**Issue by minkss** [darknessomi/musicbox#245]
前一天安装完，就报了一个错误
$musicbox
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/NetEase_MusicBox-0.2.1.1-py2.6.egg/NEMbox/__init__.py", line 18, in start
    nembox_menu.start_fork(version)
  File "/usr/lib/python2.6/site-packages/NetEase_MusicBox-0.2.1.1-py2.6.egg/NEMbox/menu.py", line 152, in start_fork
    Menu().start()
  File "/usr/lib/python2.6/site-packages/NetEase_MusicBox-0.2.1.1-py2.6.egg/NEMbox/menu.py", line 286, in start
    self.dispatch_enter(idx)
  File "/usr/lib/python2.6/site-packages/NetEase_MusicBox-0.2.1.1-py2.6.egg/NEMbox/menu.py", line 573, in dispatch_enter
    self.datalist = netease.dig_info(songs, 'songs')
  File "/usr/lib/python2.6/site-packages/NetEase_MusicBox-0.2.1.1-py2.6.egg/NEMbox/api.py", line 534, in dig_info
    url, quality = geturl(data[i])
  File "/usr/lib/python2.6/site-packages/NetEase_MusicBox-0.2.1.1-py2.6.egg/NEMbox/api.py", line 168, in geturl
    enc_id = encrypted_id(song_id)
  File "/usr/lib/python2.6/site-packages/NetEase_MusicBox-0.2.1.1-py2.6.egg/NEMbox/api.py", line 70, in encrypted_id
    m = hashlib.md5(song_id)
TypeError: md5() argument 1 must be string or read-only buffer, not bytearray
[minks@zx musicbox-master]$ /usr/lib/python2.6/site-packages/requests-2.9.1-py2.6.egg/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/lib/python2.6/site-packages/requests-2.9.1-py2.6.egg/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

本想放弃，因为最近刚在接触python就进去看了，我把
 m = hashlib.md5(song_id)
改成了
 m = hashlib.md5(str(song_id))
前天我就改了这么一下，就可以了，可以播放了。
昨天我打开电脑，到了空格播放的时候就不行了，
我不知道该怎么改了

 Unknown option -aad Thread-1421:
                                                                                                                       Traceback (most recent call last):          顺序播放 [                                 ] (00:00/00:01)
                 File "/usr/lib/python2.6/threading.py", line 532, in __bootstrap_inner
                           网易云音乐 > 排行榜 > 云音乐新歌榜                              self.run()
                                                                                                       File "/usr/lib/python2.6/threading.py", line 484, in run
                         self.__target(*self.__args, **self.__kwargs)5期 >
                           1. 莉莉安  -  徐佳莹  < 我是歌手第四季 第4  File "/usr/lib/python2.6/site-packages/NetEase_MusicBox-0.2.1.1-py2.6.egg/NEMbox/player.py", line 69, in runInThread我是歌手第四季 第5期 >
                           3. 默  -  黄致列  < 我    self.popen_handler.stdin.write("V " + str(self.info["playing_volume"]) + "\n")
                           4. 信仰  -  张信哲  < 我是歌手第四季 第4期 >                                                            IOError: [Errno 32] 断开的管道    5. 野子  -  苏运莹  < 我是歌手第四季 第3期 >

**Comment by minkss** [comment]
补充一下我用的是centos6.7  python2.6.6

**Comment by kigawas** [comment]
更新到新版本，使用python 2.7+
