### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by LanceGe** [darknessomi/musicbox#248]
Traceback (most recent call last):
  File "/usr/local/bin/musicbox", line 9, in <module>
    load_entry_point('NetEase-MusicBox==0.2.1.2', 'console_scripts', 'musicbox')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.4/dist-packages/NEMbox/__init__.py", line 37
    print 'NetEase-MusicBox installed version:' + version
                                              ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by taizilongxu** [comment]
得用python2.x运行, 你这个是3.4哦

**Comment by LanceGe** [comment]
喔喔吼的。。
