### ISSUE TITLE
登陆崩溃问题

### ISSUE THREAD

**Issue by i2bin** [darknessomi/musicbox#254]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/__init__.py", line 18, in start
    nembox_menu.start_fork(version)
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/menu.py", line 162, in start_fork
    Menu().start()
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/menu.py", line 296, in start
    self.dispatch_enter(idx)
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/menu.py", line 527, in dispatch_enter
    self.choice_channel(idx)
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/menu.py", line 732, in choice_channel
    myplaylist = self.request_api(self.netease.user_playlist, self.userid)
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/menu.py", line 676, in request_api
    self.storage.database['user']['nickname'] = user_info['profile']['nickname']
KeyError: 'profile'

**Comment by i2bin** [comment]
一个没怎么用过的账号

**Comment by i2bin** [comment]
好了，网易的邮箱，但没登陆过网易音乐
