### ISSUE TITLE
Ubuntu-gnome 15.10 运行失败

### ISSUE THREAD

**Issue by amitbha** [darknessomi/musicbox#256]
Traceback (most recent call )：
File "/usr/local/lib/python2.7/dist-packages/NEMbox/__init__.py", line 18, in start
                        nembox_menu.start_fork(version)
File "/usr/local/lib/python2.7/dist-packages/NEMbox/menu.py", line 174, in start_fork
                        Menu().start()
File "/usr/local/lib/python2.7/dist-packages/NEMbox/menu.py", line 199, in start
                       self.ui.build_menu(self.datatype, self.title, self.datalist, self.offset, self.index, self.step, self.START)
File "/usr/local/lib/python2.7/dist-packages/NEMbox/ui.py", line 209, in build_menu
                     self.screen.addstr(i - offset + 9, self.startcol, str(i) + '. ' + datalist[i])
                     error: addstr() returned ERR           %     

看了下版本，应该是最新的
$musicbox -v
NetEase-MusicBox installed version:0.2.1.5
Traceback (most recent call last):
File "/usr/local/bin/musicbox", line 9, in <module>
                load_entry_point('NetEase-MusicBox==0.2.1.5', 'console_scripts', 'musicbox')()
File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 549, in load_entry_point
               return get_distribution(dist).load_entry_point(group, name)
File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2542, in load_entry_point
               return ep.load()
File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2202, in load
               return self.resolve()
File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2208, in resolve
               module = __import__(self.module_name, fromlist=['__name__'], level=0)
File "/usr/local/lib/python2.7/dist-packages/NEMbox/__init__.py", line 39, in <module>
               print 'NetEase-MusicBox latest version:' + latest
        TypeError: cannot concatenate 'str' and 'int' objects

**Comment by amitbha** [comment]
怎么没人理我，我把首页说明都看了，也没发现哪里操作不对啊

**Comment by amitbha** [comment]
sb help!

**Comment by darknessomi** [comment]
Debian-gnome 好好地，我也没办法复现。。。。。

**Comment by amitbha** [comment]
可能是系统出问题了，打印出错信息都乱七八糟的
还是继续web吧

**Comment by Catofes** [comment]
感觉是 cursers 的锅。。。
