### ISSUE TITLE
Crash Log

### ISSUE THREAD

**Issue by github4dogg** [darknessomi/musicbox#289]
Traceback (most recent call last):
                                    File "/usr/local/bin/musicbox", line 9, in <module>
                                                                                           load_entry_point('NetEase-MusicBox==0.1.5.3', 'console_scripts', 'musicbox')()
                                                      File "/Library/Python/2.7/site-packages/NetEase_MusicBox-0.1.5.3-py2.7.egg/NEMbox/__init__.py", line 12, in start
                                                      Menu().start()
                                                                      File "/Library/Python/2.7/site-packages/NetEase_MusicBox-0.1.5.3-py2.7.egg/NEMbox/menu.py", line 253, in start
                                                                   self.player.play(datatype, datalist, idx)
                                                                                                              File "/Library/Python/2.7/site-packages/NetEase_MusicBox-0.1.5.3-py2.7.egg/NEMbox/player.py", line 90, in play
                                                                                                           self.pause()
    File "/Library/Python/2.7/site-packages/NetEase_MusicBox-0.1.5.3-py2.7.egg/NEMbox/player.py", line 129, in pause
                                                                                                                        os.kill(self.popen_handler.pid, signal.SIGSTOP)
                                                  AttributeError: 'NoneType' object has no attribute 'pid'

**Comment by darknessomi** [comment]
```sudo pip install NetEase-MusicBox``` 😊
