### ISSUE TITLE
Arch Linux报错ImportError:No module named 'menu'

### ISSUE THREAD

**Issue by razrLeLe** [darknessomi/musicbox#30]
-> % musicbox
Traceback (most recent call last):
  File "/usr/bin/musicbox", line 9, in <module>
    load_entry_point('NetEase-MusicBox==0.1.3.0', 'console_scripts', 'musicbox')()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 519, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2630, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2310, in load
    return self.resolve()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2316, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.4/site-packages/NetEase_MusicBox-0.1.3.0-py3.4.egg/src/__init__.py", line 8, in <module>
    from menu import Menu
ImportError: No module named 'menu'

**Comment by darknessomi** [comment]
请用 py2.7

**Comment by razrLeLe** [comment]
赞～问题解决，成功启动！
还有貌似必须使用python2-setuptools而不是python-setuptools～

建议在README里面这两个地方注明一下。

**Comment by darknessomi** [comment]
python-setuptools 在别的包管理里是指python2-setuptools的
