### ISSUE TITLE
分类歌单会导致程序跳出 请检查

### ISSUE THREAD

**Issue by ruizhipeng** [darknessomi/musicbox#320]
我的发行版 archlinux  也有可能是我的依赖有问题 但是我是用git拉下来编译的 应该可能性不大
信息如下
`roy@Dipper ~ % musicbox`
`/usr/lib/python2.7/site-packages/gtk-2.0/gtk/__init__.py:127: RuntimeWarning: PyOS_InputHook is not available for interactive use of PyGTK`
 ` set_interactive(1)`
`1 roy@Dipper ~ %     `

**Comment by kigawas** [comment]
怎么reproduce？

这个warning不会影响运行

**Comment by ruizhipeng** [comment]
但是会跳出 不能获取下一级列表 如果需要其他信息我再发

**Comment by kigawas** [comment]
__init__.py开头加上：
import gtk
gtk.set_interactive(False)

**Comment by ruizhipeng** [comment]
不解决问题 同时导致musicbox完全不能启动

**Comment by kigawas** [comment]
我这里解决了warning的问题（虽然原本就不影响使用），

有可能是你的环境有问题，结合之前warning覆盖歌单，有可能是你的终端有问题

**Comment by ruizhipeng** [comment]
Traceback (most recent call last):
                                                                                   File "/usr/bin/musicbox", line 9, in <module> 0. 全站置顶
                  ->    load_entry_point('NetEase-MusicBox==0.2.2.9', 'console_scripts', 'musicbox')()
                                                                                                        File "/usr/lib/python2.7/site-packages/NEMbox/__init__.py", line 20, in start
                                                                             nembox_menu.start_fork(version)
  File "/usr/lib/python2.7/site-packages/NEMbox/menu.py", line 174, in start_fork
                                                                                     Menu().start()
                                                                                                     File "/usr/lib/python2.7/site-packages/NEMbox/menu.py", line 338, in start
                                                                       self.dispatch_enter(idx)
                                                                                                 File "/usr/lib/python2.7/site-packages/NEMbox/menu.py", line 607, in dispatch_enter
                                                                            self.datalist = netease.dig_info(data['callback'](), self.datatype)
                                     File "/usr/lib/python2.7/site-packages/NEMbox/api.py", line 655, in dig_info
         soup = BeautifulSoup(data, 'lxml')
                                             File "/usr/lib/python2.7/site-packages/bs4/__init__.py", line 156, in __init__
                   % ",".join(features))
                                        bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

**Comment by ruizhipeng** [comment]
找到问题所在

**Comment by ruizhipeng** [comment]
需要安装 python2-lxml 希望添加到依赖里面

**Comment by kigawas** [comment]
@ruizhipeng beautiful soup 4的依赖已经包含了lxml
