### ISSUE TITLE
可能是新api的锅 播放会自动终止

### ISSUE THREAD

**Issue by ruizhipeng** [darknessomi/musicbox#325]
`Traceback (most recent call last):
                                    File "/usr/bin/musicbox", line 9, in <module>
                                                                                     load_entry_point('NetEase-MusicBox==0.2.2.10', 'console_scripts', 'musicbox')()
                                                          File "/usr/lib/python2.7/site-packages/NEMbox/__init__.py", line 20, in start
                               nembox_menu.start_fork(version)
                                                                File "/usr/lib/python2.7/site-packages/NEMbox/menu.py", line 172, in start_fork
                                       Menu().start()
                                                       File "/usr/lib/python2.7/site-packages/NEMbox/menu.py", line 433, in start
                         self.player.play_and_pause(idx)
                                                          File "/usr/lib/python2.7/site-packages/NEMbox/player.py", line 246, in play_and_pause
                                       self.switch()
                                                      File "/usr/lib/python2.7/site-packages/NEMbox/player.py", line 254, in switch
                           self.stop()
                                        File "/usr/lib/python2.7/site-packages/NEMbox/player.py", line 262, in stop
           self.popen_handler.stdin.write('Q\n')
                                                IOError: [Errno 32] 断开的管道
                                                                              musicbox  9.70s user 1.25s system 2% cpu 6:06.46 total`
系统 archlinux x64

**Comment by ruizhipeng** [comment]
也有可能是我环境不对 望告知怎么修改

**Comment by Catofes** [comment]
我说的嘛，管道还是要捕获异常的诶～

**Comment by ruizhipeng** [comment]
@Catofes 那请问有什么解决办法么？

**Comment by Catofes** [comment]
等更新～

**Comment by kigawas** [comment]
@Catofes 
正常情况是不用的，切换歌曲太快就会出现这种情况

**Comment by Catofes** [comment]
@kigawas  真的不加try嘛？ 因为管道断开导致程序崩溃不对吧
