### ISSUE TITLE
程序中断后无法启动

### ISSUE THREAD

**Issue by panw3i** [darknessomi/musicbox#339]
Traceback (most recent call last):
                                    File "/usr/local/bin/musicbox", line 9, in <module>
                                                                                           load_entry_point('musicbox==0.1.2.4', 'console_scripts', 'musicbox')()
                                                        File "/usr/local/lib/python2.7/dist-packages/src/__init__.py", line 11, in start
                                 Menu().start()
                                                 File "/usr/local/lib/python2.7/dist-packages/src/menu.py", line 95, in start
                      self.ui.build_menu(self.datatype, self.title, self.datalist, self.offset, self.index, self.step)
             File "/usr/local/lib/python2.7/dist-packages/src/ui.py", line 64, in build_menu
                                                                                                self.screen.addstr(i - offset +8, 19, str(i) + '. ' + datalist[i])
                                                       _curses.error: addstr() returned ERR

**Comment by kigawas** [comment]
重启终端试试
