### ISSUE TITLE
菜单中的＂6每日推荐＂出错了，平台没改变也未做修改，今早打开时发现的

### ISSUE THREAD

**Issue by hehh2001** [darknessomi/musicbox#359]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/NEMbox/__init__.py", line 20, in start
    nembox_menu.start_fork(version)
  File "/usr/lib/python2.7/site-packages/NEMbox/menu.py", line 172, in start_fork
    Menu().start()
  File "/usr/lib/python2.7/site-packages/NEMbox/menu.py", line 305, in start
    self.dispatch_enter(idx)
  File "/usr/lib/python2.7/site-packages/NEMbox/menu.py", line 583, in dispatch_enter
    self.choice_channel(idx)
  File "/usr/lib/python2.7/site-packages/NEMbox/menu.py", line 812, in choice_channel
    self.datalist = self.netease.dig_info(myplaylist, self.datatype)
  File "/usr/lib/python2.7/site-packages/NEMbox/api.py", line 584, in dig_info
    for i in range(0, len(data)):
TypeError: object of type 'bool' has no len()

**Comment by hehh2001** [comment]
有时是直接退出了，

**Comment by redapple0204** [comment]
是你那里有问题吧，我的好好的
![2016-08-04 16 04 18](https://cloud.githubusercontent.com/assets/16254644/17394720/35796920-5a5d-11e6-92a4-b011824bd86a.png)
que ding ni shi fo den确定你是否登陆成功
