### ISSUE TITLE
tty 下无法自动播放下一首并报错卡死

### ISSUE THREAD

**Issue by kj54321** [darknessomi/musicbox#362]
如题。使用 putty 连接机器，可以选择并播放第一首曲目，但当播放下一首时就报错卡死....
```
Traceback (most recent call last):
                                    File "/bin/musicbox", line 9, in <module>
                                                                                 load_entry_point('NetEase-MusicBox==0.2.2.10', 'console_scripts', 'musicbox')()
                                                                                 File "/usr/lib/python2.7/site-packages/NEMbox/__init__.py", line 20, in start
                                                                                  nembox_menu.start_fork(version)
                                   File "/usr/lib/python2.7/site-packages/NEMbox/menu.py", line 172, in start_fork
                                      Menu().start()
                                                      File "/usr/lib/python2.7/site-packages/NEMbox/menu.py", line 421, in start
                                                    'player_info']['idx'])
                                                                            File "/usr/lib/python2.7/site-packages/NEMbox/player.py", line 240, in play_and_pause
     self.pause()
                   File "/usr/lib/python2.7/site-packages/NEMbox/player.py", line 273, in pause
                   self.popen_handler.stdin.write('P\n')
                                                        IOError: [Errno 32] Broken pipe
```
看报错，貌似是play and pause的功能 有问题.......希望可以修复。

**Comment by kigawas** [comment]
应该是因为mpg123失去响应
