### ISSUE TITLE
random start failure

### ISSUE THREAD

**Issue by rtlanceroad** [darknessomi/musicbox#382]
This is quite strange. When I first open it, i got following error:

```
lee@sakura ~ $ musicbox 
Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/musicbox", line 11, in <module>
    load_entry_point('NetEase-MusicBox==0.2.3.1', 'console_scripts', 'musicbox')()
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 2589, in load_entry_point
    return ep.load()
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 2249, in load
    return self.resolve()
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 2255, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib64/python2.7/site-packages/NEMbox/__init__.py", line 19, in <module>
    from .menu import Menu
  File "/usr/lib64/python2.7/site-packages/NEMbox/menu.py", line 31, in <module>
    from .osdlyrics import show_lyrics_new_process
  File "/usr/lib64/python2.7/site-packages/NEMbox/osdlyrics.py", line 21, in <module>
    config = Config()
  File "/usr/lib64/python2.7/site-packages/NEMbox/config.py", line 114, in __init__
    self.generate_config_file()
  File "/usr/lib64/python2.7/site-packages/NEMbox/config.py", line 131, in generate_config_file
    f.write(json.dumps(self.default_config, indent=2))
TypeError: write() argument 1 must be unicode, not str
```
Then I open it again, it works without error.

Environment:
```
> OS:            Gentoo Linux
> PKG ver:    0.2.3.1
> Python ver: 2.7.12
```

I am totally a python newbie, I can't fix it. But i am a good guy, I report it.

**Comment by kigawas** [comment]
Thanks!
Change to:
  f.write(json.dumps(self.default_config, indent=2).decode('u8')

**Comment by rtlanceroad** [comment]
Great. I believe this will be applied in the next release. Since this is fixed, I'll close it.

**Comment by rtlanceroad** [comment]
@darknessomi Sorry for this irrelevant msg, but what's the name of your github avatar girl? Can you show me the source? Thank you.
