### ISSUE TITLE
桌面歌词边框不透明问题。

### ISSUE THREAD

**Issue by redapple0204** [darknessomi/musicbox#385]
就像这样
![2016-09-17 06 44 34](https://cloud.githubusercontent.com/assets/16254644/18603278/a6bb04e2-7ca2-11e6-9e32-d4d4ef6ff7d7.png)

好难看啊.....请问怎么样才能变成透明？
顺便说下.....怎么改变歌词颜色和字体大小？

**Comment by kigawas** [comment]
config.json里面指定osdlyrics_transparent为true

**Comment by redapple0204** [comment]
@kigawas 已经是ture了啊
>{
  "global_previous": {
    "default": "<ctrl><alt>k", 
    "describe": "Global keybind for previous song.Uses gtk notation for keybinds.", 
    "value": "<ctrl><alt>k"
  }, 
  "osdlyrics_transparent": {
    "default": True, 
    "describe": "Desktop lyrics transparent bg.", 
    "value": True
  }, 
  "global_play_pause": {
    "default": "<ctrl><alt>p", 
    "describe": "Global keybind for play/pause.Uses gtk notation for keybinds.", 
    "value": "<ctrl><alt>p"
  }, 
  "osdlyrics": {
    "default": True, 
    "describe": "Desktop lyrics for musicbox.", 
    "value": True
  }, 
  "osdlyrics_background": {
    "default": "rgba(100, 100, 100, 120)", 
    "describe": "Desktop lyrics background color.", 
    "value": "rgba(100, 100, 100, 120)"
  }, 
  "global_next": {
    "default": "<ctrl><alt>j", 
    "describe": "Global keybind for next song.Uses gtk notation for keybinds.", 
    "value": "<ctrl><alt>j"
  }, 
  "osdlyrics_color": {
    "default": [
      225, 
      248, 
      113
    ], 
    "describe": "Desktop lyrics RGB Color.", 
    "value": [
      225, 
      248, 
      113
    ]
  }, 
  "cache": {
    "default": false, 
    "describe": "A toggle to enable cache function or not. Set value to true to enable it.", 
    "value": false
  }, 
  "aria2c_parameters": {
    "default": [], 
    "describe": "The additional parameters when aria2c start to download something.", 
    "value": []
  }, 
  "osdlyrics_on_top": {
    "default": true, 
    "describe": "Desktop lyrics OnTopHint.", 
    "value": true
  }, 
  "version": 6, 
  "mpg123_parameters": {
    "default": [], 
    "describe": "The additional parameters when mpg123 start.", 
    "value": []
  }, 
  "music_quality": {
    "default": 2, 
    "describe": "Select the quality of the music. May be useful when network is terrible. 0 for high quality, 1 for medium and 2 for low.", 
    "value": 2
  }, 
  "translation": {
    "default": true, 
    "describe": "Foreign language lyrics translation.", 
    "value": true
  }, 
  "notifier": {
    "default": true, 
    "describe": "Notifier when switching songs.", 
    "value": true
  }, 
  "osdlyrics_font": {
    "default": [
      "Decorative", 
      16
    ], 
    "describe": "Desktop lyrics font-family and font-size.", 
    "value": [
      "Decorative", 
      16
    ]
  }
}

**Comment by kigawas** [comment]
JSON格式不对，里面True都是小写

**Comment by redapple0204** [comment]
@kigawas 仍然不行，我甚至在/usr/local/lib/python2.7/dist-packages/NEMbox/menu.py都改了，也不行。

**Comment by kigawas** [comment]
看一下日志，和config.json在一个地方

**Comment by redapple0204** [comment]
@kigawas 
>################################################################################
2016-09-17 08:18:55,841 - DEBUG - NEMbox.config:124: Load config json data failed.
2016-09-17 08:18:55,872 - WARNING - NEMbox.menu:47: keybinder module not installed.
2016-09-17 08:18:55,872 - WARNING - NEMbox.menu:48: Not binding global hotkeys.
################################################################################
2016-09-17 09:02:15,215 - DEBUG - NEMbox.config:124: Load config json data failed.
2016-09-17 09:02:15,946 - WARNING - NEMbox.menu:47: keybinder module not installed.
2016-09-17 09:02:15,946 - WARNING - NEMbox.menu:48: Not binding global hotkeys.
################################################################################
2016-09-17 10:23:41,742 - DEBUG - NEMbox.config:124: Load config json data failed.
2016-09-17 10:23:41,773 - WARNING - NEMbox.menu:47: keybinder module not installed.
2016-09-17 10:23:41,773 - WARNING - NEMbox.menu:48: Not binding global hotkeys.
################################################################################
2016-09-17 10:25:16,522 - DEBUG - NEMbox.config:124: Load config json data failed.
2016-09-17 10:25:16,552 - WARNING - NEMbox.menu:47: keybinder module not installed.
2016-09-17 10:25:16,552 - WARNING - NEMbox.menu:48: Not binding global hotkeys.
2016-09-17 10:25:23,319 - ERROR - NEMbox.menu:429: string indices must be integers
################################################################################
2016-09-17 10:28:42,823 - DEBUG - NEMbox.config:124: Load config json data failed.
2016-09-17 10:28:42,854 - WARNING - NEMbox.menu:47: keybinder module not installed.
2016-09-17 10:28:42,854 - WARNING - NEMbox.menu:48: Not binding global hotkeys.
################################################################################
2016-09-17 10:29:09,784 - DEBUG - NEMbox.config:124: Load config json data failed.
2016-09-17 10:29:09,814 - WARNING - NEMbox.menu:47: keybinder module not installed.
2016-09-17 10:29:09,814 - WARNING - NEMbox.menu:48: Not binding global hotkeys.
################################################################################
2016-09-17 10:32:31,566 - DEBUG - NEMbox.config:124: Load config json data failed.
2016-09-17 10:32:31,597 - WARNING - NEMbox.menu:47: keybinder module not installed.
2016-09-17 10:32:31,597 - WARNING - NEMbox.menu:48: Not binding global hotkeys.
2016-09-17 10:32:45,147 - ERROR - NEMbox.menu:429: string indices must be integers
################################################################################
2016-09-17 10:35:26,718 - DEBUG - NEMbox.config:124: Load config json data failed.
2016-09-17 10:35:26,748 - WARNING - NEMbox.menu:47: keybinder module not installed.
2016-09-17 10:35:26,748 - WARNING - NEMbox.menu:48: Not binding global hotkeys.
2016-09-17 10:35:44,308 - INFO - NEMbox.cache:90: Old:http://m1.music.126.net/dwyi1bAqNGHCVHi-EFvGAQ==/1424967084977459.mp3. New:http://m10.music.126.net/20160917110044/0536c7af73864ddf4a71bd03f301c83f/ymusic/56bc/0658/de22/c30ced049629e5d49a3d2b3335548770.mp3
2016-09-17 10:35:57,436 - DEBUG - NEMbox.cache:114: 429450375 Cache OK
################################################################################
2016-09-17 10:42:40,401 - WARNING - NEMbox.menu:47: keybinder module not installed.
2016-09-17 10:42:40,401 - WARNING - NEMbox.menu:48: Not binding global hotkeys.
################################################################################
2016-09-17 10:43:39,940 - WARNING - NEMbox.menu:47: keybinder module not installed.
2016-09-17 10:43:39,941 - WARNING - NEMbox.menu:48: Not binding global hotkeys.
################################################################################
################################################################################
################################################################################
2016-09-17 10:45:28,433 - WARNING - NEMbox.menu:47: keybinder module not installed.
2016-09-17 10:45:28,433 - WARNING - NEMbox.menu:48: Not binding global hotkeys.
################################################################################
2016-09-17 10:47:18,583 - WARNING - NEMbox.menu:47: keybinder module not installed.
2016-09-17 10:47:18,583 - WARNING - NEMbox.menu:48: Not binding global hotkeys.

**Comment by redapple0204** [comment]
@kigawas 
python-keybinder这个包已经安装

**Comment by kigawas** [comment]
写的JSON有问题，qt成功安装了

**Comment by redapple0204** [comment]
@kigawas 咦？json文件不是在上面嘛，我没有发现问题啊
话说这个错误是好象是因为没有安装keybinder模块导致的，在menu.py里有
>try:
    import keybinder
    BINDABLE = True
except ImportError:
    BINDABLE = False
    log.warn('keybinder module not installed.')
    log.warn('Not binding global hotkeys.')

但是pip安装不行

>Collecting keybinder

 >Could not find a version that satisfies the requirement keybinder (from versions: )
No matching distribution found for keybinder

源里虽然有python-keybinder,但是安装还是无效。

**Comment by kigawas** [comment]
keybinder只和全局快捷键有关....

**Comment by redapple0204** [comment]
@kigawas 那就奇怪了，这是bug？

**Comment by kigawas** [comment]
你把config.json删掉了，默认生成一个，然后把对应的false改成true（改完检查下JSON是不是合法http://jsonlint.com）

**Comment by redapple0204** [comment]
@kigawas 1.重新生成仍然不行.....
2.跳出了这个错误
>/usr/lib/python2.7/dist-packages/gtk-2.0/gtk/__init__.py:127: RuntimeWarning: PyOS_InputHook is not available for interactive use of PyGTK
  set_interactive(1)

3.会不会和我用的桌面环境有关系，我用gnome-fallback。

**Comment by redapple0204** [comment]
@kigawas 另外
>Error: Parse error on line 75:
...		"value": true	},
---------------------^
Expecting 'STRING', got 'EOF'

**Comment by kigawas** [comment]
这个错误是快捷键相关的....

**Comment by redapple0204** [comment]
@kigawas 哦.......
也就是说.....这真的是bug？

**Comment by kigawas** [comment]
不能透明可能是qt的问题。
把osdlyrics.py这里的if去掉看一下能不能透明
```python
if config.get_item("osdlyrics_transparent"):
    self.setAttribute(QtCore.Qt.WA_TranslucentBackground)
```

**Comment by redapple0204** [comment]
@kigawas 不行，会报错
>Traceback (most recent call last):
  File "/usr/local/bin/musicbox", line 7, in <module>
    from NEMbox import start
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/__init__.py", line 19, in <module>
    from .menu import Menu
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/menu.py", line 31, in <module>
    from .osdlyrics import show_lyrics_new_process
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/osdlyrics.py", line 43
    config.get_item("osdlyrics_transparent"):
    ^
IndentationError: unexpected indent

**Comment by kigawas** [comment]
```python
if config.get_item("osdlyrics_transparent"):
    self.setAttribute(QtCore.Qt.WA_TranslucentBackground)
```
改成
```python
self.setAttribute(QtCore.Qt.WA_TranslucentBackground)
```
缩进要一致

**Comment by redapple0204** [comment]
@kigawas 
>Traceback (most recent call last):
  File "/usr/local/bin/musicbox", line 7, in <module>
    from NEMbox import start
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/__init__.py", line 19, in <module>
    from .menu import Menu
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/menu.py", line 31, in <module>
    from .osdlyrics import show_lyrics_new_process
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/osdlyrics.py", line 43
    self.setAttribute(QtCore.Qt.WA_TranslucentBackground)
    ^
IndentationError: unexpected indent

**Comment by kigawas** [comment]
http://pastebin.com/pihZuSHt

**Comment by redapple0204** [comment]
@kigawas 依旧不行。

**Comment by kigawas** [comment]
那就应该是qt的问题了

**Comment by redapple0204** [comment]
@kigawas 会不会qt在gnome-fallback模式（即gnome2/mate模式）下有问题？

**Comment by redapple0204** [comment]
@kigawas 既然这样有没有办法把窗口框框弄小一点.....太大了黑黑的很难看。

**Comment by kigawas** [comment]
https://github.com/darknessomi/musicbox/blob/master/NEMbox/osdlyrics.py#L55

```
self.setMinimumSize(600, 50)
self.resize(600, 60)
```

**Comment by redapple0204** [comment]
@kigawas OK,thx
看来只能临时这样了。

**Comment by kigawas** [comment]
Gnome3没有这个问题，你可以更新一下

**Comment by redapple0204** [comment]
@kigawas 话说这个提示真的没有办法去掉吗？我有强迫症....
>/usr/lib/python2.7/dist-packages/gtk-2.0/gtk/__init__.py:127: RuntimeWarning: PyOS_InputHook is not available for interactive use of PyGTK

**Comment by redapple0204** [comment]
@kigawas OK

**Comment by kigawas** [comment]
下一个版本会增加是否打开全局快捷键的选项来解决这个问题

**Comment by redapple0204** [comment]
@kigawas 1.ok,thx
2.but....在今天没有折腾桌面歌词的时候还不会啊。

**Comment by kigawas** [comment]
@redapple0204
keybinder这个模块用来绑定全局快捷键的问题

**Comment by kigawas** [comment]
@redapple0204
keybinder这个模块（用来绑定全局快捷键）的问题

**Comment by kigawas** [comment]
@redapple0204
keybinder这个模块（用来绑定全局快捷键）的问题

**Comment by RADiEnCe** [comment]
Expect string那条错误信息。。。说不定“true”得有引号？（别问我。我瞎凑热闹）
