### ISSUE TITLE
选到歌曲精选的时候会崩溃

### ISSUE THREAD

**Issue by moboard** [darknessomi/musicbox#404]
~ musicbox
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/NEMbox/__init__.py", line 27, in start
    nembox_menu.start_fork(version)
  File "/usr/lib/python2.7/site-packages/NEMbox/menu.py", line 176, in start_fork
    Menu().start()
  File "/usr/lib/python2.7/site-packages/NEMbox/menu.py", line 340, in start
    self.dispatch_enter(idx)
  File "/usr/lib/python2.7/site-packages/NEMbox/menu.py", line 609, in dispatch_enter
    self.datalist = netease.dig_info(data['callback'](), self.datatype)
  File "/usr/lib/python2.7/site-packages/NEMbox/api.py", line 669, in dig_info
    soup = BeautifulSoup(data, 'lxml')
  File "/usr/lib/python2.7/site-packages/bs4/__init__.py", line 165, in __init__
    % ",".join(features))
FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

```

之前一直都没有问题的，这是提示要安装哪个包？

**Comment by moboard** [comment]
补充，是精选歌单-分类精选，然后才崩溃的。

**Comment by kigawas** [comment]
安装lxml

**Comment by moboard** [comment]
重新安装了几个包之后，提示稍变了下：
`FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?`
再安装pypy-lxml，还是崩溃。

**Comment by kigawas** [comment]
确定是pypy？根据python版本安装python2-lxml或python3-lxml（类似名字）

**Comment by moboard** [comment]
库里只有一个pypy-lxml最相似，包括aur里。

**Comment by r0ger3am** [comment]
要用python3

**Comment by kigawas** [comment]
直接`pip install lxml`应该也可以

**Comment by sqltxt** [comment]
树莓派留爪
easy_install lxml
python setup.py install
