### ISSUE TITLE
今天更新后不能运行

### ISSUE THREAD

**Issue by moboard** [darknessomi/musicbox#422]
早上习惯性的滚一下，发现不能运行
archinux+python3.5

> > musicbox 
> > zsh: 可执行文件格式错误: musicbox

**Comment by kigawas** [comment]
先试试mpg123能不能运行，如果能运行就重装musicbox

**Comment by moboard** [comment]
mpg123没问题，删除了安装，提示有很多文件存在，用的yaourt -Rd删除的，竟然还有残留，手动删除那些残留，就可以重新安装了。
不过在精选那里又崩溃一次，再试又没有重现。
```
->>> musicbox
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/NEMbox/__init__.py", line 27, in start
    nembox_menu.start_fork(version)
  File "/usr/lib/python2.7/site-packages/NEMbox/menu.py", line 177, in start_fork
    Menu().start()
  File "/usr/lib/python2.7/site-packages/NEMbox/menu.py", line 338, in start
    self.dispatch_enter(idx)
  File "/usr/lib/python2.7/site-packages/NEMbox/menu.py", line 635, in dispatch_enter
    self.datalist = netease.dig_info(data['callback'](), self.datatype)
```

继续试用 中
