### ISSUE TITLE
0.2.3.7 查看评论时抛出异常

### ISSUE THREAD

**Issue by MichaelVipub** [darknessomi/musicbox#441]
当要查看一首歌曲的评论时，抛出异常，异常如下
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/__init__.py", line 26, in start
    nembox_menu.start_fork(version)
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/menu.py", line 176, in start_fork
    Menu().start()
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/menu.py", line 328, in start
    self.dispatch_enter(idx)
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/menu.py", line 685, in dispatch_enter
    hotcomments = comments['hotComments']
TypeError: list indices must be integers, not unicode
```

异常之后无法进行任何操作，只能用其他终端kill了。

**Comment by MichaelVipub** [comment]
重新安装以后没有复现问题。关闭
