### ISSUE TITLE
It can't play music normally

### ISSUE THREAD

**Issue by sheacoding** [darknessomi/musicbox#444]
Exception in thread Thread-37:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/player.py", line 114, in runInThread
    self.popen_handler.stdin.write(b'\nL ' + new_url.encode('utf-8') + b'\n')
IOError: [Errno 32] Broken pipe

**Comment by Catofes** [comment]
Please make sure you have `mpg122` installed
