### ISSUE TITLE
pycrypto 安装出错

### ISSUE THREAD

**Issue by Marlin-Na** [darknessomi/musicbox#445]
系统是 openSUSE tumbleweed ，完整报错如下，我看不太懂，但似乎是因为安装 pycrypto 时出错。

有什么建议吗？谢谢。

```
$ pip3 install NetEase-MusicBox

Collecting NetEase-MusicBox
  Using cached NetEase-MusicBox-0.2.3.7.tar.gz
Requirement already satisfied: requests in /usr/lib/python3.5/site-packages (from NetEase-MusicBox)
Collecting BeautifulSoup4 (from NetEase-MusicBox)
  Using cached beautifulsoup4-4.5.1-py3-none-any.whl
Collecting pycrypto (from NetEase-MusicBox)
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out. (read timeout=15)",)': /packages/60/db/645aa9af249f059cc3a368b118de33889219e0362141e75d4eaf6f80f163/pycrypto-2.6.1.tar.gz
  Downloading pycrypto-2.6.1.tar.gz (446kB)
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 232, in _error_catcher
    yield
  File "/usr/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 314, in read
    data = self._fp.read(amt)
  File "/usr/lib/python3.5/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 60, in read
    data = self.__fp.read(amt)
  File "/usr/lib64/python3.5/http/client.py", line 433, in read
    n = self.readinto(b)
  File "/usr/lib64/python3.5/http/client.py", line 473, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib64/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib64/python3.5/ssl.py", line 924, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib64/python3.5/ssl.py", line 786, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib64/python3.5/ssl.py", line 570, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3.5/site-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python3.5/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python3.5/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python3.5/site-packages/pip/req/req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "/usr/lib/python3.5/site-packages/pip/download.py", line 821, in unpack_url
    hashes=hashes
  File "/usr/lib/python3.5/site-packages/pip/download.py", line 659, in unpack_http_url
    hashes)
  File "/usr/lib/python3.5/site-packages/pip/download.py", line 882, in _download_http_url
    _download_url(resp, link, content_file, hashes)
  File "/usr/lib/python3.5/site-packages/pip/download.py", line 603, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "/usr/lib/python3.5/site-packages/pip/utils/hashes.py", line 46, in check_against_chunks
    for chunk in chunks:
  File "/usr/lib/python3.5/site-packages/pip/download.py", line 571, in written_chunks
    for chunk in chunks:
  File "/usr/lib/python3.5/site-packages/pip/utils/ui.py", line 139, in iter
    for x in it:
  File "/usr/lib/python3.5/site-packages/pip/download.py", line 560, in resp_read
    decode_content=False):
  File "/usr/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 357, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 324, in read
    flush_decoder = True
  File "/usr/lib64/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 237, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
pip._vendor.requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out.

```

**Comment by kigawas** [comment]
没网

**Comment by Marlin-Na** [comment]
@kigawas  orz 原来如此，，网是连着的，但 ping pypi.python.org 有将近一半的丢包率，前几次试也有下载一半然后出现这样的错误，但总算知道原因了。。 我之后挂代理去试一下
