### ISSUE TITLE
在非歌曲清单介面按“shift+C”缓存会异常，并退出

### ISSUE THREAD

**Issue by kimw** [darknessomi/musicbox#455]
菜单介面的异常：

```
Traceback (most recent call last):
  File "/home/kimw/.local/lib/python3.5/site-packages/NEMbox/__init__.py", line 26, in start
    nembox_menu.start_fork(version)
  File "/home/kimw/.local/lib/python3.5/site-packages/NEMbox/menu.py", line 176, in start_fork
    Menu().start()
  File "/home/kimw/.local/lib/python3.5/site-packages/NEMbox/menu.py", line 573, in start
    args=(s['song_id'], s['song_name'], s['artist'], s[
TypeError: string indices must be integers
```

歌单介面的异常：

```
Traceback (most recent call last):
  File "/home/kimw/.local/lib/python3.5/site-packages/NEMbox/__init__.py", line 26, in start
    nembox_menu.start_fork(version)
  File "/home/kimw/.local/lib/python3.5/site-packages/NEMbox/menu.py", line 176, in start_fork
    Menu().start()
  File "/home/kimw/.local/lib/python3.5/site-packages/NEMbox/menu.py", line 573, in start
    args=(s['song_id'], s['song_name'], s['artist'], s[
TypeError: string indices must be integers
```

**Comment by jinxingxing** [comment]
+1

**Comment by gaoyifan** [comment]
+1

**Comment by zdzliqian** [comment]
+1

**Comment by pilgrimaz** [comment]
+1
