### ISSUE TITLE
缓存歌曲时必须先播放这个列表，否则会出现异常

### ISSUE THREAD

**Issue by kimw** [darknessomi/musicbox#457]
缓存歌曲时必须先播放这个列表，否则会出现异常。发生异常后，缓存线程失控，必须完全退出程序才能进行缓存。

```
Exception in thread Thread-4:
  Traceback (most recent call last):
    File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
      self.run()
    File "/usr/lib/python3.5/threading.py", line 862, in run
      self._target(*self._args, **self._kwargs)
    File "/home/kimw/p/musicbox/NEMbox/player.py", line 472, in cacheSong1time
      self.cache.start_download()
    File "/home/kimw/p/musicbox/NEMbox/cache.py", line 121, in start_download
      onExit(song_id, full_path)
    File "/home/kimw/p/musicbox/NEMbox/player.py", line 467, in cacheExit
      self.songs[str(song_id)]['cache'] = path
  KeyError: '3052693'
```

分析：应该时缓存前没有在 Palyer.songs 中保存当前 play list 的内容。

**Comment by darknessomi** [comment]
经审阅：该 issue 已过时、已在讨论中解答、或长期无有效跟进，先行关闭。如问题在现行版本仍存在，请重新提交并附上环境与复现步骤。
