### ISSUE TITLE
macOS单曲循环播放，播着播着就报这个错误。

### ISSUE THREAD

**Issue by Waking-Y** [darknessomi/musicbox#465]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/NEMbox/__init__.py", line 26, in start
    nembox_menu.start_fork(version)
  File "/usr/local/lib/python3.5/site-packages/NEMbox/menu.py", line 176, in start_fork
    Menu().start()
  File "/usr/local/lib/python3.5/site-packages/NEMbox/menu.py", line 425, in start
    self.player.play_and_pause(idx)
  File "/usr/local/lib/python3.5/site-packages/NEMbox/player.py", line 263, in play_and_pause
    self.switch()
  File "/usr/local/lib/python3.5/site-packages/NEMbox/player.py", line 271, in switch
    self.stop()
  File "/usr/local/lib/python3.5/site-packages/NEMbox/player.py", line 280, in stop
    self.popen_handler.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe

**Comment by MaYunFei** [comment]
我是顺序播放的时候
