### ISSUE TITLE
进入'每日推荐‘出错

### ISSUE THREAD

**Issue by silbertmonaphia** [darknessomi/musicbox#472]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/__init__.py", line 26, in start
    nembox_menu.start_fork(version)
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/menu.py", line 176, in start_fork
    Menu().start()
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/menu.py", line 328, in start
    self.dispatch_enter(idx)
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/menu.py", line 608, in dispatch_enter
    self.choice_channel(idx)
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/menu.py", line 876, in choice_channel
    self.datalist = self.netease.dig_info(myplaylist, self.datatype)
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/api.py", line 618, in dig_info
    for i in range(0, len(data)):
TypeError: object of type 'bool' has no len()

**Comment by lroolle** [comment]
这个还没有 Fix 吗？

**Comment by kigawas** [comment]
@Iroolle

没发现有这个问题，最新版试一下

**Comment by silbertmonaphia** [comment]
@kigawas
刚更新到0.2.3.9
然而，还是一样的问题....- -

**Comment by lroolle** [comment]
重新登录就好了

**Comment by silbertmonaphia** [comment]
@lroolle    ok了,thx ~
