### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by zhangchuheng123** [darknessomi/musicbox#474]
1 搜索歌手列出来很多歌手的时候，数字点错了，就会出现out of index
2 出现Exception之后无法返回

**Comment by boygao1992** [comment]
碰到同样问题，当专辑列表中歌曲数少，例如只有1首，按大于1的数字键就会报错并锁死UI

**Comment by jemyzhang** [comment]
网易云音乐 > 艺术家 > 陈绮贞 > 陈绮贞的热门歌曲
播放到最后一首的时候,出现traceback
```
Traceback (most recent call last):
File "/usr/local/bin/musicbox", line 11, in <module>
sys.exit(start())
File "/usr/local/lib/python3.5/dist-packages/NEMbox/__init__.py", line 40, in start
nembox_menu.start_fork(version)
File "/usr/local/lib/python3.5/dist-packages/NEMbox/menu.py", line 177, in start_fork
 Menu().start()
File "/usr/local/lib/python3.5/dist-packages/NEMbox/menu.py", line 418, in start
if isinstance(self.datalist[idx], dict) and self.datalist[idx]['song_id'] == self.player.playing_id:
IndexError: list index out of range
```

**Comment by wangKuma** [comment]
fix
