### ISSUE TITLE
适配小窗口的终端tty设备

### ISSUE THREAD

**Issue by atmouse-** [darknessomi/musicbox#495]
我是在开发板上安装musicbox，终端窗口很小，只有40x15
启动的时候直接就这样了，或者在播放的时候，缩小窗口到一定程度也会。
```
Traceback (most recent call last):
  File "/usr/bin/musicbox", line 11, in <module>
    load_entry_point('NetEase-MusicBox==0.2.3.7', 'console_scripts', 'musicbox')()
  File "/usr/lib/python2.7/site-packages/NEMbox/__init__.py", line 26, in start
    nembox_menu.start_fork(version)
  File "/usr/lib/python2.7/site-packages/NEMbox/menu.py", line 176, in start_fork
    Menu().start()
  File "/usr/lib/python2.7/site-packages/NEMbox/menu.py", line 587, in start
    self.offset, self.index, self.step, self.START)
  File "/usr/lib/python2.7/site-packages/NEMbox/ui.py", line 236, in build_menu
    self.addstr(5, self.startcol, title, curses.color_pair(1))
  File "/usr/lib/python2.7/site-packages/NEMbox/ui.py", line 90, in addstr
    self.screen.addstr(args[0], args[1], args[2].encode('utf-8'), *args[3:])
_curses.error: addstr() returned ERR
```

增加一个小窗口的模式吧

**Comment by atmouse-** [comment]
又好像没什么用。
