### ISSUE TITLE
无法登录 TypeError: Only byte strings can be passed to C code

### ISSUE THREAD

**Issue by fffx** [darknessomi/musicbox#523]
ubuntu: 16.04 
musicbox:  0.2.4
登录方式: 手机号
**Traceback**:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/NEMbox/__init__.py", line 26, in start
    nembox_menu.start_fork(version)
  File "/usr/local/lib/python3.5/dist-packages/NEMbox/menu.py", line 177, in start_fork
    Menu().start()
  File "/usr/local/lib/python3.5/dist-packages/NEMbox/menu.py", line 334, in start
    self.dispatch_enter(idx)
  File "/usr/local/lib/python3.5/dist-packages/NEMbox/menu.py", line 629, in dispatch_enter
    self.choice_channel(idx)
  File "/usr/local/lib/python3.5/dist-packages/NEMbox/menu.py", line 877, in choice_channel
    myplaylist = self.request_api(self.netease.user_playlist, self.userid)
  File "/usr/local/lib/python3.5/dist-packages/NEMbox/menu.py", line 814, in request_api
    data = self.ui.build_login()
  File "/usr/local/lib/python3.5/dist-packages/NEMbox/ui.py", line 532, in build_login
    login_info = self.netease.login(local_account, local_password)
  File "/usr/local/lib/python3.5/dist-packages/NEMbox/api.py", line 251, in login
    return self.phone_login(username, password)
  File "/usr/local/lib/python3.5/dist-packages/NEMbox/api.py", line 274, in phone_login
    data = encrypted_request(text)
  File "/usr/local/lib/python3.5/dist-packages/NEMbox/api.py", line 99, in encrypted_request
    encText = aesEncrypt(aesEncrypt(text, nonce), secKey)
  File "/usr/local/lib/python3.5/dist-packages/NEMbox/api.py", line 108, in aesEncrypt
    encryptor = AES.new(secKey, 2, '0102030405060708')
  File "/usr/local/lib/python3.5/dist-packages/Crypto/Cipher/AES.py", line 264, in new
    return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/Crypto/Cipher/__init__.py", line 130, in _create_cipher
    return modes[mode](factory, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/Crypto/Cipher/_mode_cbc.py", line 232, in _create_cbc_cipher
    cipher_state = factory._create_base_cipher(kwargs)
  File "/usr/local/lib/python3.5/dist-packages/Crypto/Cipher/AES.py", line 131, in _create_base_cipher
    expect_byte_string(key)
  File "/usr/local/lib/python3.5/dist-packages/Crypto/Util/_raw_api.py", line 175, in expect_byte_string
    raise TypeError("Only byte strings can be passed to C code")
TypeError: Only byte strings can be passed to C code

```

**Comment by fangxing204** [comment]
删除 $HOME/.netease-music 下的文件后, 重新登录就好了

**Comment by Xuyuanp** [comment]
一样的问题，删掉文件也没用

**Comment by kigawas** [comment]
重装pycrypto试一下

2017年5月11日(木) 18:34 Xuyuan Pang <notifications@github.com>:

**Comment by Xuyuanp** [comment]
我换成python3.5就好了

**Comment by fffx** [comment]
@Xuyuanp 从我的`Traceback`可以看到，我确实用的python3.5

**Comment by Xuyuanp** [comment]
@fffx 不清楚，我之前用3.6就出你这个问题，切换成3.5就ok了
