### ISSUE TITLE
操作精选歌单->分类精选时报错

### ISSUE THREAD

**Issue by aduo** [darknessomi/musicbox#525]
`Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/NEMbox/__init__.py", line 26, in start
    nembox_menu.start_fork(version)
  File "/usr/local/lib/python3.6/site-packages/NEMbox/menu.py", line 177, in start_fork
    Menu().start()
  File "/usr/local/lib/python3.6/site-packages/NEMbox/menu.py", line 304, in start
    self.dispatch_enter(idx)
  File "/usr/local/lib/python3.6/site-packages/NEMbox/menu.py", line 673, in dispatch_enter
    self.datalist = netease.dig_info(data['callback'](), self.datatype)
  File "/usr/local/lib/python3.6/site-packages/NEMbox/api.py", line 694, in dig_info
    soup = BeautifulSoup(data, 'lxml')
  File "/usr/local/lib/python3.6/site-packages/bs4/__init__.py", line 165, in __init__
    % ",".join(features))
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?`

**Comment by kigawas** [comment]
pip install lxml

2017年4月10日(月) 19:18 Dranker D <notifications@github.com>:
