### ISSUE TITLE
每日推荐异常推出

### ISSUE THREAD

**Issue by zxt50330** [darknessomi/musicbox#529]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/NEMbox/__init__.py", line 26, in start
    nembox_menu.start_fork(version)
  File "/Library/Python/2.7/site-packages/NEMbox/menu.py", line 177, in start_fork
    Menu().start()
  File "/Library/Python/2.7/site-packages/NEMbox/menu.py", line 334, in start
    self.dispatch_enter(idx)
  File "/Library/Python/2.7/site-packages/NEMbox/menu.py", line 629, in dispatch_enter
    self.choice_channel(idx)
  File "/Library/Python/2.7/site-packages/NEMbox/menu.py", line 897, in choice_channel
    self.datalist = self.netease.dig_info(myplaylist, self.datatype)
  File "/Library/Python/2.7/site-packages/NEMbox/api.py", line 620, in dig_info
    for i in range(0, len(data)):
TypeError: object of type 'bool' has no len()

**Comment by kigawas** [comment]
我这里好的，可能是网络问题

**Comment by zxt50330** [comment]
登录太久，cookie无效了，重新登录下就好啦

**Comment by zxt50330** [comment]
api.py
 
    def recommend_playlist(self):
        try:
            action = 'http://music.163.com/weapi/v1/discovery/recommend/songs?csrf_token='  # NOQA
            self.session.cookies.load()
            csrf = ''
            for cookie in self.session.cookies:
                if cookie.name == '__csrf':
                    csrf = cookie.value
            if csrf == '':
                return False  # 这里直接返回false 导致后面出错

**Comment by kigawas** [comment]
okay 会在下个版本修复
