### ISSUE TITLE
ImportError: cannot import name 'byte_string'

### ISSUE THREAD

**Issue by sunhuachuang** [darknessomi/musicbox#537]
启动的时候，会报错， 这是为啥呢？
```
➜  ~ musicbox                                                      
Traceback (most recent call last):
  File "/usr/bin/musicbox", line 11, in <module>
    load_entry_point('NetEase-MusicBox==0.2.4.0', 'console_scripts', 'musicbox')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 560, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2648, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2302, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2308, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.6/site-packages/NEMbox/__init__.py", line 19, in <module>
    from .menu import Menu
  File "/usr/lib/python3.6/site-packages/NEMbox/menu.py", line 29, in <module>
    from .api import NetEase
  File "/usr/lib/python3.6/site-packages/NEMbox/api.py", line 31, in <module>
    from Crypto.Cipher import AES
  File "/usr/lib/python3.6/site-packages/Crypto/Cipher/__init__.py", line 78, in <module>
    from Crypto.Cipher._mode_ecb import _create_ecb_cipher
  File "/usr/lib/python3.6/site-packages/Crypto/Cipher/_mode_ecb.py", line 29, in <module>
    from Crypto.Util._raw_api import (load_pycryptodome_raw_lib,
  File "/usr/lib/python3.6/site-packages/Crypto/Util/_raw_api.py", line 33, in <module>
    from Crypto.Util.py3compat import byte_string
ImportError: cannot import name 'byte_string'
```
python  信息：
```
➜  ~ python --version
Python 3.6.1
```

```
➜  ~ sudo pip install NetEase-MusicBox -i https://pypi.douban.com/simple
Requirement already satisfied: NetEase-MusicBox in /usr/lib/python3.6/site-packages
Requirement already satisfied: requests in /usr/lib/python3.6/site-packages (from NetEase-MusicBox)
Requirement already satisfied: BeautifulSoup4 in /usr/lib/python3.6/site-packages (from NetEase-MusicBox)
Requirement already satisfied: pycrypto in /usr/lib/python3.6/site-packages (from NetEase-MusicBox)
Requirement already satisfied: future in /usr/lib/python3.6/site-packages (from NetEase-MusicBox)
```

**Comment by sunhuachuang** [comment]
我已经查明原因了，原因是直接用 pip install 出来的 pycrypto这个包是有问题的包，删掉之后，用系统自带的包，比如我的是arch ,pacman -S python-crypto，即可解决这个问题。容我去检查一下是豆瓣的mirrors出的问题，还是官方源pypi上也有此问题。
