### ISSUE TITLE
Some errors when I opened it  (ubuntu LTS16.04)

### ISSUE THREAD

**Issue by cjhonlyone** [darknessomi/musicbox#538]
root@c416593819:/home/caojiahui# musicbox
Traceback (most recent call last):
  File "/usr/local/bin/musicbox", line 7, in <module>
    from NEMbox import start
  File "/usr/local/lib/python3.5/dist-packages/NEMbox/__init__.py", line 19, in <module>
    from .menu import Menu
  File "/usr/local/lib/python3.5/dist-packages/NEMbox/menu.py", line 29, in <module>
    from .api import NetEase
  File "/usr/local/lib/python3.5/dist-packages/NEMbox/api.py", line 33, in <module>
    from bs4 import BeautifulSoup
  File "/usr/lib/python3/dist-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/lib/python3/dist-packages/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/usr/lib/python3/dist-packages/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: module 'html5lib.treebuilders' has no attribute '_base'

**Comment by wangKuma** [comment]
尝试使用 git 方式安装，再试一下
