### ISSUE TITLE
播放时出现错误 centos7

### ISSUE THREAD

**Issue by 329379172** [darknessomi/musicbox#542]
Exception in thread Thread-1:                                                                                 
Traceback (most recent call last):                                               
File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
File "/usr/local/lib/python3.6/threading.py", line 864, in run                                                                                  
self._target(*self._args, **self._kwargs)                                     
File "/usr/local/lib/python3.6/site-packages/NetEase_MusicBox-0.2.4.0-py3.6.egg/NEMbox/player.py", line 94, in runInThread                                                                                      
strout = self.popen_handler.stdout.readline().decode('utf-8')                                      
AttributeError: 'NoneType' object has no attribute 'stdout'

**Comment by 329379172** [comment]
sudo yum install mpg123.x86_64 -y

安装了这个库就好了
