### ISSUE TITLE
raspbian系统下安装报错

### ISSUE THREAD

**Issue by bbdgvt** [darknessomi/musicbox#552]
错误如下：
pi@raspberrypi:~ $ pip3 install NetEase-MusicBox
Downloading/unpacking NetEase-MusicBox
  Downloading NetEase-MusicBox-0.2.4.0.tar.gz
  Running setup.py (path:/tmp/pip-build-rdqc28na/NetEase-MusicBox/setup.py) egg_info for package NetEase-MusicBox

Requirement already satisfied (use --upgrade to upgrade): requests in /usr/lib/python3/dist-packages (from NetEase-MusicBox)
Downloading/unpacking BeautifulSoup4 (from NetEase-MusicBox)
  Downloading beautifulsoup4-4.6.0-py3-none-any.whl (86kB): 86kB downloaded
Downloading/unpacking pycrypto (from NetEase-MusicBox)
  Downloading pycrypto-2.6.1.tar.gz (446kB): 430kB downloaded
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 186, in read
    data = self._fp.read(amt)
  File "/usr/lib/python3.4/http/client.py", line 500, in read
    return super(HTTPResponse, self).read(amt)
  File "/usr/lib/python3.4/http/client.py", line 539, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.4/socket.py", line 371, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.4/ssl.py", line 745, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.4/ssl.py", line 617, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1198, in prepare_files
    do_download,
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1376, in unpack_url
    self.session,
  File "/usr/lib/python3/dist-packages/pip/download.py", line 572, in unpack_http_url
    download_hash = _download_url(resp, link, temp_location)
  File "/usr/lib/python3/dist-packages/pip/download.py", line 433, in _download_url
    for chunk in resp_read(4096):
  File "/usr/lib/python3/dist-packages/pip/download.py", line 421, in resp_read
    chunk_size, decode_content=False):
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 256, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 201, in read
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out.

Storing debug log for failure in /home/pi/.pip/pip.log

**Comment by bbdgvt** [comment]
换个国内的源就好了例如 pip3 install NetEase-MusicBox -i http://pypi.douban.com/simple
