### ISSUE TITLE
经常播放完一首歌就卡住

### ISSUE THREAD

**Issue by Sherlock-Holo** [darknessomi/musicbox#563]
播放完一首歌后会卡住，然后切换下一首歌偶尔可以继续播放
切换歌后或者卡住时会报错
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 11: ordinal not in range(128)

Logged from file playUnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 11: ordinal not in range(128)
```
                                    File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
Traceback (most recent call last):                                                                      msg = self.format(record)                          File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
            File "/usr/lib/python2.7/logging/__init__.py", line 734, in format                          msg = self.format(record)                                                                        return fmt.format(record)
            File "/usr/lib/python2.7/logging/__init__.py", line 734, in format                               File "/usr/lib/python2.7/logging/__init__.py", line 476, in format                          return fmt.format(record)
                                                            raise e                                          File "/usr/lib/python2.7/logging/__init__.py", line 476, in format           UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 11: ordinal not in range(128)              raise e
                                              Logged from file playUnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 11: ordinal not in range(128)
                                              Logged from file player.py, line 152
```

**Comment by out0fmemory** [comment]
请帮忙试一下，在上面链接的pull里边已经修复 #568

**Comment by Sherlock-Holo** [comment]
不好意思因为用着arch cn源的包，所以不太方便测试，现在merge了cn源也更新了，正在测试

**Comment by Sherlock-Holo** [comment]
连续播放了一两个小时，暂时没见问题

**Comment by Sherlock-Holo** [comment]
@out0fmemory 播放完后歌会停住不再播放下去的现象还是有

**Comment by Sherlock-Holo** [comment]
具体表现为下一首歌的进度是到了最后例如3:24/3:24这样
