### ISSUE TITLE
Ubuntu 16.04 安装GUI版本后报错

### ISSUE THREAD

**Issue by Ficklee** [darknessomi/musicbox#570]
在安装云音乐ubuntu 16.04 x64的deb后报错
错误logging：
```python
Traceback (most recent call last):
  File "/usr/local/bin/musicbox", line 9, in <module>
    load_entry_point('NetEase-MusicBox==0.2.4.1', 'console_scripts', 'musicbox')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/dist-packages/NEMbox/__init__.py", line 19, in <module>
    from .menu import Menu
  File "/usr/local/lib/python3.5/dist-packages/NEMbox/menu.py", line 29, in <module>
    from .api import NetEase
  File "/usr/local/lib/python3.5/dist-packages/NEMbox/api.py", line 33, in <module>
    from bs4 import BeautifulSoup
  File "/usr/lib/python3/dist-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/lib/python3/dist-packages/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/usr/lib/python3/dist-packages/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: module 'html5lib.treebuilders' has no attribute '_base'
```
是否是因为两者冲突所致？是否需要卸载？

**Comment by darknessomi** [comment]
经审阅：该 issue 已过时、已在讨论中解答、或长期无有效跟进，先行关闭。如问题在现行版本仍存在，请重新提交并附上环境与复现步骤。
