### ISSUE TITLE
ImportError: cannot import name set_file_position

### ISSUE THREAD

**Issue by shiywang** [darknessomi/musicbox#587]
when I upgrade my system from fedora 25 to fedora 26, musicbox just can't works.
```
Traceback (most recent call last):
  File "/usr/bin/musicbox", line 11, in <module>
    load_entry_point('NetEase-MusicBox==0.2.4.1', 'console_scripts', 'musicbox')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2649, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2303, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2309, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.linux-x86_64/egg/NEMbox/__init__.py", line 19, in <module>
  File "build/bdist.linux-x86_64/egg/NEMbox/menu.py", line 29, in <module>
  File "build/bdist.linux-x86_64/egg/NEMbox/api.py", line 34, in <module>
  File "/usr/lib/python2.7/site-packages/requests/__init__.py", line 60, in <module>
    from .packages.urllib3.exceptions import DependencyWarning
  File "/usr/lib/python2.7/site-packages/requests/packages/__init__.py", line 29, in <module>
    import urllib3
  File "/usr/lib/python2.7/site-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 39, in <module>
    from .util.request import set_file_position
ImportError: cannot import name set_file_position
```
➜  musicbox git:(master) uname -a
Linux shiywang 4.11.9-300.fc26.x86_64 #1 SMP Wed Jul 5 16:21:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by darknessomi** [comment]
经审阅：该 issue 已过时、已在讨论中解答、或长期无有效跟进，先行关闭。如问题在现行版本仍存在，请重新提交并附上环境与复现步骤。
