### ISSUE TITLE
搜索中文时的backspace删除问题

### ISSUE THREAD

**Issue by blueswill** [darknessomi/musicbox#616]
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/NEMbox/__init__.py", line 40, in start
    nembox_menu.start_fork(version)
  File "/usr/lib/python3.6/site-packages/NEMbox/menu.py", line 177, in start_fork
    Menu().start()
  File "/usr/lib/python3.6/site-packages/NEMbox/menu.py", line 334, in start
    self.dispatch_enter(idx)
  File "/usr/lib/python3.6/site-packages/NEMbox/menu.py", line 742, in dispatch_enter
    self.datalist = ui.build_search('songs')
  File "/usr/lib/python3.6/site-packages/NEMbox/ui.py", line 497, in build_search
    song_name = self.get_param('搜索歌曲：')
  File "/usr/lib/python3.6/site-packages/NEMbox/ui.py", line 641, in get_param
    info = info.decode('utf8')
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 30-31: invalid continuation byte

```
我猜原因是按backspace键时没有正确处理UTF-8的编码问题，导致一个正常的文字编码被截断无法正常读取。如果没有backspace删除操作的话就是正常的。

**Comment by darknessomi** [comment]
经审阅：该 issue 已过时、已在讨论中解答、或长期无有效跟进，先行关闭。如问题在现行版本仍存在，请重新提交并附上环境与复现步骤。
