### ISSUE TITLE
无法缓存至本地

### ISSUE THREAD

**Issue by Minys233** [darknessomi/musicbox#620]
在按下`ctrl+c`缓存至本地时会报错：
环境是Ubuntu 16.04，python 3.6.1
> Traceback (most recent call last):
  File "/home/minys/anaconda3/lib/python3.6/site-packages/NEMbox/__init__.py", line 40, in start
    nembox_menu.start_fork(version)
  File "/home/minys/anaconda3/lib/python3.6/site-packages/NEMbox/menu.py", line 177, in start_fork
    Menu().start()
  File "/home/minys/anaconda3/lib/python3.6/site-packages/NEMbox/menu.py", line 594, in start
    args=(s['song_id'], s['song_name'], s['artist'], s[
TypeError: string indices must be integers

看过源码之后发现`menu.py`中控制下载时有这么一段代码：
```python
elif key == ord('C'):
    s = self.datalist[idx]
    cache_thread = threading.Thread(
        target=self.player.cacheSong1time,
        args=(s['song_id'], s['song_name'], s['artist'], s[
            'mp3_url']))
    cache_thread.start()
```
这段代码判断用户按下相应的按键之后，接了这么一句`s = self.datalist[idx]`，而在该文件开头处`self.datalist`是一个列表，其内容是`['排行榜', '艺术家', '新碟上架', '精选歌单', '我的歌单', '主播电台', '每日推荐', '私人FM', '搜索', '帮助']`，所以不管怎么用s肯定只是其中一个字符串，所以之后调用函数过程中也绝对会出错。

**Comment by darknessomi** [comment]
经审阅：该 issue 已过时、已在讨论中解答、或长期无有效跟进，先行关闭。如问题在现行版本仍存在，请重新提交并附上环境与复现步骤。
