### ISSUE TITLE
一首歌放完后放下一首歌的时候，终端有python程序的代码错误提示

### ISSUE THREAD

**Issue by oakszyjrnrdy** [darknessomi/musicbox#630]
```
                                                              File "/home/linjian/anaconda2/lib/python2.7/logging/__ini_ _ z Z Zline 476,做我的猫  -  满舒克  < 做我的猫 >
                                                 raise e
                            ==========                       ] (01:06/04:01 'ascii' codec can't decode                  我却静不下心分析
                     好想对着我说唇语
Traceback (most recent call last):
                                    File "/home/linjian/anaconda2/lib/python2.7/logging/__init__.py", line 861, in emit
                    1. 骆驼  -  薛之谦  < 骆驼 >
                    2. 遥远的歌  -  刘惜君  < 你好，旧时光 原声带 >/anaconda2/lib/python2.7/logging/__init__.py", line -> 3. 做我的猫  -  满舒克  < 做我的猫 >
                                   return fmt.format(record)
                                                              File "/home/linjian/anaconda2/lib/python2.7/logging/__init__.py", line 476, in format
                                                 raise e
                                                        UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 11: ordinal not in range(128)
                                                    Logged from file player.py, line 152

```

**Comment by wangKuma** [comment]
你好，感谢使用，能否依据以下格式提供详细信息
## 所使用的系统版本
## 所使用产品版本
## 问题的详细描述与截图(如果可以)
## 如何复现该问题
