### ISSUE TITLE
播放过程中不定时卡死

### ISSUE THREAD

**Issue by kmahyyg** [darknessomi/musicbox#637]
```python
Exception in thread Thread-1:
Traceback (most recent call last):
File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
                  self.run()
File "/usr/lib/python3.5/threading.py", line 862, in run
                  self._target(*self._args, **self._kwargs)
File "/usr/local/lib/python3.5/dist-packages/NetEase_MusicBox-0.2.4.2-py3.5.egg/NEMbox/player.py", line 97, in runInThread
                  strout = self.popen_handler.stdout.readline().decode('utf-8')
                         UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 26: invalid continuation byte
```

报错信息如上，Deepin Linux 15.5 ，Git clone方式安装，

听     >孙燕姿 - 我怀念的    会卡死，其他歌目前没发现，无法确定具体故障原因。

账号为年费会员

**Comment by kmahyyg** [comment]
Confirmed: Network stability issues
