### ISSUE TITLE
从今早开始突然无法使用

### ISSUE THREAD

**Issue by kmahyyg** [darknessomi/musicbox#649]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/NetEase_MusicBox-0.2.4.2-py3.5.egg/NEMbox/__init__.py", line 40, in start
    nembox_menu.start_fork(version)
  File "/usr/local/lib/python3.5/dist-packages/NetEase_MusicBox-0.2.4.2-py3.5.egg/NEMbox/menu.py", line 177, in start_fork
    Menu().start()
  File "/usr/local/lib/python3.5/dist-packages/NetEase_MusicBox-0.2.4.2-py3.5.egg/NEMbox/menu.py", line 304, in start
    self.dispatch_enter(idx)
  File "/usr/local/lib/python3.5/dist-packages/NetEase_MusicBox-0.2.4.2-py3.5.egg/NEMbox/menu.py", line 629, in dispatch_enter
    self.choice_channel(idx)
  File "/usr/local/lib/python3.5/dist-packages/NetEase_MusicBox-0.2.4.2-py3.5.egg/NEMbox/menu.py", line 897, in choice_channel
    self.datalist = self.netease.dig_info(myplaylist, self.datatype)
  File "/usr/local/lib/python3.5/dist-packages/NetEase_MusicBox-0.2.4.2-py3.5.egg/NEMbox/api.py", line 654, in dig_info
    for i in range(0, len(data)):
TypeError: object of type 'bool' has no len()

尝试过w之后重新登录，提示登录成功。但是选其他菜单项又提示未登录

pip3方式安装 linux

**Comment by kmahyyg** [comment]
尝试安装deepin自带的网易云音乐，仍然无法播放，怀疑网络问题。还麻烦维护者能告知下哪里可以看debug level的日志吗？

**Comment by wangKuma** [comment]
tail -f ~/.netease-musicbox/musicbox.log
是在播放时报错吗？
用的哪一个版本的？

**Comment by kmahyyg** [comment]
> NetEase_MusicBox-0.2.4.2-py3.5.egg

**Comment by kmahyyg** [comment]
Solved.   Close #649

问题确定： Deepin Linux系统网络代理设置异常。
