### ISSUE TITLE
安装后运行不起来

### ISSUE THREAD

**Issue by fasureChou** [darknessomi/musicbox#677]
执行musicbox命令之后的输出
`Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/NEMbox/__init__.py", line 40, in start
    nembox_menu.start_fork(version)
  File "/usr/local/lib/python3.6/site-packages/NEMbox/menu.py", line 175, in start_fork
    Menu().update_alert(version)
  File "/usr/local/lib/python3.6/site-packages/NEMbox/menu.py", line 148, in update_alert
    latest = Menu().check_version()
  File "/usr/local/lib/python3.6/site-packages/NEMbox/menu.py", line 158, in check_version
    mobilesignin = self.netease.daily_signin(0)
  File "/usr/local/lib/python3.6/site-packages/NEMbox/api.py", line 316, in daily_signin
    return self.httpRequest('POST', action, data)
  File "/usr/local/lib/python3.6/site-packages/NEMbox/api.py", line 243, in httpRequest
    self.rawHttpRequest(method, action, query, urlencoded, callback, timeout)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

系统 macOS 10.13.3
mpg123单独可以播放本地音乐
日志内容：
`2018-03-01 18:26:35,745 - WARNING - NEMbox.ui:36: Qt dbus module is not installed.
2018-03-01 18:26:35,745 - WARNING - NEMbox.ui:37: Osdlyrics is not available.
2018-03-01 18:26:35,767 - WARNING - NEMbox.osdlyrics:28: PyQt4 module not installed.
2018-03-01 18:26:35,767 - WARNING - NEMbox.osdlyrics:29: Osdlyrics Not Available.
################################################################################
2018-03-01 18:32:47,143 - WARNING - NEMbox.ui:36: Qt dbus module is not installed.
2018-03-01 18:32:47,144 - WARNING - NEMbox.ui:37: Osdlyrics is not available.
2018-03-01 18:32:47,152 - WARNING - NEMbox.osdlyrics:28: PyQt4 module not installed.
2018-03-01 18:32:47,152 - WARNING - NEMbox.osdlyrics:29: Osdlyrics Not Available.`

**Comment by darknessomi** [comment]
经审阅：该 issue 已过时、已在讨论中解答、或长期无有效跟进，先行关闭。如问题在现行版本仍存在，请重新提交并附上环境与复现步骤。
