### ISSUE TITLE
打开某些歌单会出错

### ISSUE THREAD

**Issue by PythonYXY** [darknessomi/musicbox#681]
`Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/NEMbox/api.py", line 134, in geturl
    return geturl_v1(song)
  File "/usr/local/lib/python3.6/site-packages/NEMbox/api.py", line 142, in geturl_v1
    if song['hMusic'] and quality <= 0:
KeyError: 'hMusic'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/NEMbox/__init__.py", line 40, in start
    nembox_menu.start_fork(version)
  File "/usr/local/lib/python3.6/site-packages/NEMbox/menu.py", line 177, in start_fork
    Menu().start()
  File "/usr/local/lib/python3.6/site-packages/NEMbox/menu.py", line 334, in start
    self.dispatch_enter(idx)
  File "/usr/local/lib/python3.6/site-packages/NEMbox/menu.py", line 681, in dispatch_enter
    self.datalist = netease.dig_info(songs, 'songs')
  File "/usr/local/lib/python3.6/site-packages/NEMbox/api.py", line 655, in dig_info
    url, quality = geturl(data[i])
  File "/usr/local/lib/python3.6/site-packages/NEMbox/api.py", line 136, in geturl
    return geturl_v3(song)
  File "/usr/local/lib/python3.6/site-packages/NEMbox/api.py", line 174, in geturl_v3
    return song['mp3Url'], ''
KeyError: 'mp3Url'
`

**Comment by darknessomi** [comment]
经审阅：该 issue 已过时、已在讨论中解答、或长期无有效跟进，先行关闭。如问题在现行版本仍存在，请重新提交并附上环境与复现步骤。
