### ISSUE TITLE
ubuntu出现这种报错

### ISSUE THREAD

**Issue by sunmaoxiang** [darknessomi/musicbox#688]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/__init__.py", line 40, in start
    nembox_menu.start_fork(version)
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/menu.py", line 175, in start_fork
    Menu().update_alert(version)
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/menu.py", line 148, in update_alert
    latest = Menu().check_version()
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/menu.py", line 158, in check_version
    mobilesignin = self.netease.daily_signin(0)
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/api.py", line 316, in daily_signin
    return self.httpRequest('POST', action, data)
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/api.py", line 243, in httpRequest
    self.rawHttpRequest(method, action, query, urlencoded, callback, timeout)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by XAS-712** [comment]
搞不好接口改了。
用ColaV9抓包看看

**Comment by wangKuma** [comment]
你好，感谢使用，能否依据以下格式提供详细信息
## 所使用的系统版本
## 所使用版本
## 问题的详细描述与截图(如果可以)
## 如何复现该问题

**Comment by darknessomi** [comment]
经审阅：该 issue 已过时、已在讨论中解答、或长期无有效跟进，先行关闭。如问题在现行版本仍存在，请重新提交并附上环境与复现步骤。
