### ISSUE TITLE
登陆失败～

### ISSUE THREAD

**Issue by Catofes** [darknessomi/musicbox#7]
在登陆的时候会在这个地方报错
https://github.com/darknessomi/musicbox/blob/master/src/menu.py#L387
错误是没有profile字段。检查返回的data里面的确没有这个字段

是不是因为帐号是手机号的原因？

**Comment by darknessomi** [comment]
支持手机号登录

**Comment by Catofes** [comment]
报错log:（把密码删掉了，同时在报错的地方上面加了一句 pirnt data 我去新建一个帐号试试看



                   请输入登录信息， e.g: john@163.com 123456




                   18600200*** ***
[{u'account': {u'userName': u'0_m18600200672@163.com', u'status': -10, u'anonimousUser': False, u'whitelistAuthority': 0, u'baoyueVersion': 0, u'ban': 0, u'type': 0, u'id': 48727681, u'donateVersion': 0}, u'code': 200, u'bindings': [{u'expiresIn': 2147483647, u'tokenJsonStr': u'{"email":"m18600200672@163.com"}', u'url': u'', u'type': 0, u'userId': 48727681, u'refreshTime': 0, u'expired': False, u'id': 24920300}], u'loginType': 0}, ['18600200***', '***']]
                                                                                   Traceback (most recent call last):
                                                                                                                       File "/usr/bin/musicbox", line 9, in <module>
                                                                                                                                                                        load_entry_point('NetEase-MusicBox==0.1.0.1.2', 'console_scripts', 'musicbox')()
                                                           File "/usr/lib/python2.7/site-packages/NetEase_MusicBox-0.1.0.1.2-py2.7.egg/src/__init__.py", line 11, in start
                                                                                                                                                                              Menu().start()
                                                                                                                                                                                              File "/usr/lib/python2.7/site-packages/NetEase_MusicBox-0.1.0.1.2-py2.7.egg/src/menu.py", line 151, in start
                                                                                                               self.dispatch_enter(idx)
                                                                                                                                         File "/usr/lib/python2.7/site-packages/NetEase_MusicBox-0.1.0.1.2-py2.7.egg/src/menu.py", line 278, in dispatch_enter
                                                                   self.choice_channel(idx) 
                                                                                              File "/usr/lib/python2.7/site-packages/NetEase_MusicBox-0.1.0.1.2-py2.7.egg/src/menu.py", line 388, in choice_channel
                        self.username = user_info['profile']['nickname']
                                                                        KeyError: 'profile'

**Comment by Catofes** [comment]
嗯 找到问题的原因了。。

不知道是网易的问题还是啥的。。。  

用手机帐号注册顺便貌似可以得到一个以m+手机号开始的163邮箱帐号，然后这个帐号和之前的帐号是独立不相关的。于是这个新帐号没有设置昵称所以也用不了。。。

这个很奇怪，可能手机登陆用的不是 http://music.163.com/api/login  抓包看像是另外一个的地址
印象中是 http://music.163.com/api/login/cellphone 

btw 貌似163支持https登陆，改成https如何？

**Comment by darknessomi** [comment]
我的账号最先是一个163邮箱网易通行证账号，而后绑定的手机，这样登录，两种方法都可以登录，并且数据是联通的。而且当你绑定手机手机的同时还会生成一个手机号@邮箱.com的账号，这个也是可以使用的。所以，个人认为网易的账号机制是：手机号=邮箱=手机邮箱，这三个号应该在网易后台对应的是同一个UUID 才对，至于http://music.163.com/api/login/cellphone，还在测试。
有改成 https 的打算，不过感觉没必要，毕竟感觉网易本身就不靠谱。

**Comment by Catofes** [comment]
对～ 这是绑定手机的结果，三个帐号相互关联起来了。。不过貌似直接用手机注册就呵呵了。。。谁晓得呢。

cellphone回来我发个pull request

**Comment by darknessomi** [comment]
用正则搞了个自动判定。。。。
