### ISSUE TITLE
add try catch for login form ?

### ISSUE THREAD

**Issue by rfyiamcool** [darknessomi/musicbox#701]
#### verison

```
musicbox -v
NetEase-MusicBox installed version:0.2.4.3
```

#### stdout:

```
[ruifengyun@xiaorui ai_meinv (master ✗)]$ musicbox
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/NEMbox/__init__.py", line 38, in start
    nembox_menu.start_fork(version)
  File "/usr/local/lib/python2.7/site-packages/NEMbox/menu.py", line 171, in start_fork
    Menu().start()
  File "/usr/local/lib/python2.7/site-packages/NEMbox/menu.py", line 604, in start
    self.offset, self.index, self.step, self.START)
  File "/usr/local/lib/python2.7/site-packages/NEMbox/ui.py", line 298, in build_menu
    datalist[i]['song_name'], self.space,
TypeError: string indices must be integers
```

**Comment by kigawas** [comment]
Refactoring. Next release may fix it

**Comment by rfyiamcool** [comment]
yes, thank u.
