### ISSUE TITLE
win7, 怎么启动不成功呢

### ISSUE THREAD

**Issue by fhvknb** [darknessomi/musicbox#708]

**Comment by kigawas** [comment]
#707

**Comment by i042416** [comment]
启动报错：C:\Code\musicbox>musicbox
Traceback (most recent call last):
  File "C:\MyApp\py20180816\Scripts\musicbox-script.py", line 11, in <module>
    load_entry_point('NetEase-MusicBox==0.2.5.3', 'console_scripts', 'musicbox')()
  File "C:\MyApp\py20180816\lib\site-packages\netease_musicbox-0.2.5.3-py3.7.egg\NEMbox\__main__.py", line 35, in start
  File "C:\MyApp\py20180816\lib\site-packages\netease_musicbox-0.2.5.3-py3.7.egg\NEMbox\menu.py", line 112, in __init__
AttributeError: module 'signal' has no attribute 'SIGWINCH'

根据这篇[CSDN博客](https://blog.csdn.net/polyhedronx/article/details/81988335)的介绍，Windows不支持SIGWINCH.
