### ISSUE TITLE
[help wanted]实际播放的歌曲和显示的不一致

### ISSUE THREAD

**Issue by Avalon** [darknessomi/musicbox#715]
操作系统ubuntu18.04
 musicbox 0.2.5.1

1.比如上面显示的是neveda 实际播放的是当前歌单里面的另外一首歌,而且用[ ]切换的时候也是随即切换到某一首歌的，而不是播放当前播放的或者是显示的上一首/下一首。
2.没有自动播放，每次第一首播放完就会暂停。
我怀疑是装错了，反复换了好几个版本，又在ubuntu live上面装了测试一下，结果还是这样QAQ

**Comment by Avalon** [comment]
而且随机播放时只要一切歌就会立刻崩溃退出
报错：
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/NetEase_MusicBox-0.2.5.1-py3.6.egg/NEMbox/__main__.py", line 37, in start
    nembox_menu.start_fork(version)
  File "/usr/local/lib/python3.6/dist-packages/NetEase_MusicBox-0.2.5.1-py3.6.egg/NEMbox/menu.py", line 223, in start_fork
    Menu().start()
  File "/usr/local/lib/python3.6/dist-packages/NetEase_MusicBox-0.2.5.1-py3.6.egg/NEMbox/menu.py", line 371, in start
    self.next_song()
  File "/usr/local/lib/python3.6/dist-packages/NetEase_MusicBox-0.2.5.1-py3.6.egg/NEMbox/menu.py", line 236, in next_song
    self.player.next()
  File "/usr/local/lib/python3.6/dist-packages/NetEase_MusicBox-0.2.5.1-py3.6.egg/NEMbox/player.py", line 418, in next
    self.next_idx()
  File "/usr/local/lib/python3.6/dist-packages/NetEase_MusicBox-0.2.5.1-py3.6.egg/NEMbox/player.py", line 400, in next_idx
    self._swap_song()
  File "/usr/local/lib/python3.6/dist-packages/NetEase_MusicBox-0.2.5.1-py3.6.egg/NEMbox/player.py", line 360, in _swap_song
    now_songs = plist.index(self.info['idx'])
ValueError: 0 is not in list

**Comment by Avalon** [comment]
而且，随机播放时一切歌程序就会崩溃推出，报错(不知道为什么没法上传图片:-(
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/NetEase_MusicBox-0.2.5.1-py3.6.egg/NEMbox/__main__.py", line 37, in start
    nembox_menu.start_fork(version)
  File "/usr/local/lib/python3.6/dist-packages/NetEase_MusicBox-0.2.5.1-py3.6.egg/NEMbox/menu.py", line 223, in start_fork
    Menu().start()
  File "/usr/local/lib/python3.6/dist-packages/NetEase_MusicBox-0.2.5.1-py3.6.egg/NEMbox/menu.py", line 371, in start
    self.next_song()
  File "/usr/local/lib/python3.6/dist-packages/NetEase_MusicBox-0.2.5.1-py3.6.egg/NEMbox/menu.py", line 236, in next_song
    self.player.next()
  File "/usr/local/lib/python3.6/dist-packages/NetEase_MusicBox-0.2.5.1-py3.6.egg/NEMbox/player.py", line 418, in next
    self.next_idx()
  File "/usr/local/lib/python3.6/dist-packages/NetEase_MusicBox-0.2.5.1-py3.6.egg/NEMbox/player.py", line 400, in next_idx
    self._swap_song()
  File "/usr/local/lib/python3.6/dist-packages/NetEase_MusicBox-0.2.5.1-py3.6.egg/NEMbox/player.py", line 360, in _swap_song
    now_songs = plist.index(self.info['idx'])
ValueError: 0 is not in list

**Comment by Avalon** [comment]
最初说错了一部分， 0.2.5.0是正常的

**Comment by Avalon** [comment]
0.2.5.0也没法顺序播放， 每次播放了一首就停下来了

**Comment by gaffery** [comment]
我也出现了歌曲显示不一致的情况，0.2.5.0 版本能否迁移一下home目录下nemcache.sqlite文件的位置到.，或者在配置文件自定义一个路径

**Comment by OMGZui** [comment]
+1

**Comment by silentred** [comment]
一样，实际播放和选中不一致

**Comment by JasonLxj** [comment]
我也是

**Comment by gangstar902** [comment]
看来大家都出现这个问题惹
