### ISSUE TITLE
搜索无法使用

### ISSUE THREAD

**Issue by KaminoDice** [darknessomi/musicbox#718]
`Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/NEMbox/__main__.py", line 37, in start
    nembox_menu.start_fork(version)
  File "/usr/lib/python3.6/site-packages/NEMbox/menu.py", line 223, in start_fork
    Menu().start()
  File "/usr/lib/python3.6/site-packages/NEMbox/menu.py", line 605, in start
    self.offset, self.index, self.step, self.menu_starts)
  File "/usr/lib/python3.6/site-packages/NEMbox/ui.py", line 368, in build_menu
    '-> ' + str(i) + '. ' + datalist[i]['title'],
KeyError: 'title'
`

**Comment by xtremerui** [comment]
一模一样的错误 ui会强制退出 歌曲仍然在后台播放 必须要ctrl-c
osx 10.13.5
iterm Build 3.2.0beta4
