### ISSUE TITLE
键入非指令按键时崩溃

### ISSUE THREAD

**Issue by sd3326852** [darknessomi/musicbox#719]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/NEMbox/__main__.py", line 37, in start
    nembox_menu.start_fork(version)
  File "/usr/local/lib/python3.5/dist-packages/NEMbox/menu.py", line 223, in start_fork
    Menu().start()
  File "/usr/local/lib/python3.5/dist-packages/NEMbox/menu.py", line 594, in start
    if self.player.playing_id != -1:
  File "/usr/local/lib/python3.5/dist-packages/NEMbox/player.py", line 122, in playing_id
    return self.current_song['song_id']
KeyError: 'song_id'

**Comment by qvshuo** [comment]
同样的问题...请问解决了吗

**Comment by darknessomi** [comment]
与 #803 为同一问题，已在 #974 中修复。

无播放时按 `i`：`playing_id` 为 `None`，原 `!= -1` 判断无效。已改为 `is not None` 检查。

请更新到最新 master 后验证。
