### ISSUE TITLE
when searching, crashed (in master branch)

### ISSUE THREAD

**Issue by indicolite** [darknessomi/musicbox#721]
⇒  musicbox
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/NetEase_MusicBox-0.2.5.2-py3.6.egg/NEMbox/__main__.py", line 37, in start
    nembox_menu.start_fork(version)
  File "/usr/local/lib/python3.6/site-packages/NetEase_MusicBox-0.2.5.2-py3.6.egg/NEMbox/menu.py", line 223, in start_fork
    Menu().start()
  File "/usr/local/lib/python3.6/site-packages/NetEase_MusicBox-0.2.5.2-py3.6.egg/NEMbox/menu.py", line 314, in start
    self.dispatch_enter(idx)
  File "/usr/local/lib/python3.6/site-packages/NetEase_MusicBox-0.2.5.2-py3.6.egg/NEMbox/menu.py", line 743, in dispatch_enter
    self.datalist = self.search(self.datatype)
  File "/usr/local/lib/python3.6/site-packages/NetEase_MusicBox-0.2.5.2-py3.6.egg/NEMbox/menu.py", line 181, in search
    return self.api.dig_info(datalist, category)
  File "/usr/local/lib/python3.6/site-packages/NetEase_MusicBox-0.2.5.2-py3.6.egg/NEMbox/api.py", line 516, in dig_info
    return Parse.songs(data)
  File "/usr/local/lib/python3.6/site-packages/NetEase_MusicBox-0.2.5.2-py3.6.egg/NEMbox/api.py", line 140, in songs
    album_name, album_id = Parse.song_album(song)
  File "/usr/local/lib/python3.6/site-packages/NetEase_MusicBox-0.2.5.2-py3.6.egg/NEMbox/api.py", line 116, in song_album
    raise ValueError
ValueError

**Comment by darknessomi** [comment]
经审阅：该 issue 已过时、已在讨论中解答、或长期无有效跟进，先行关闭。如问题在现行版本仍存在，请重新提交并附上环境与复现步骤。
