### ISSUE TITLE
这次重构后新发布的版本就是一坨shit！！！！

### ISSUE THREAD

**Issue by out0fmemory** [darknessomi/musicbox#729]
连播放下一曲都会崩溃的版本，不知道是怎么release出来的！！！！
随机循环模式，任意播放列表都会出现

Exception in thread Thread-1:
                                                                Traceback (most recent call last):
                                                                                                    File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
                                                                                                           self.run()
                                                                                                                       File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
                                                                                                                self.__target(*self.__args, **self.__kwargs)
                   File "build/bdist.macosx-10.13-x86_64/egg/NEMbox/player.py", line 251, in run_mpg123
                                                                                                           self.next()
                                                                                                                        File "build/bdist.macosx-10.13-x86_64/egg/NEMbox/player.py", line 409, in next
                                                               self.next_idx()
                                                                                File "build/bdist.macosx-10.13-x86_64/egg/NEMbox/player.py", line 386, in next_idx
                           self.shuffle_order()
                                                 File "build/bdist.macosx-10.13-x86_64/egg/NEMbox/player.py", line 323, in shuffle_order
                                                                                                                                            self.order.clear()
                   AttributeError: 'list' object has no attribute 'clear'

**Comment by neroxps** [comment]
You can you up.
