### ISSUE TITLE
0.2.5.3根本用不了

### ISSUE THREAD

**Issue by cmlingyi** [darknessomi/musicbox#736]
新用户，运行musicbox
打开任何菜单都提示“这里什么都没有 -，-”；
登录的时候 我确定账号密码是对的 但是一直提示“艾玛，登录信息好像不对呢 (O_O)#”；

参考#732回滚到23bedaf05972c63fe2512c3e1915e15ec7b75ca7后运行musicbox报错，提示：
Traceback (most recent call last):
  File "/Users/CocoChen/.pyenv/versions/3.7.0/bin/musicbox", line 11, in <module>
    load_entry_point('NetEase-MusicBox==0.2.4.2', 'console_scripts', 'musicbox')()
  File "/Users/CocoChen/.pyenv/versions/3.7.0/lib/python3.7/site-packages/NetEase_MusicBox-0.2.4.2-py3.7.egg/NEMbox/__init__.py", line 38, in start
  File "/Users/CocoChen/.pyenv/versions/3.7.0/lib/python3.7/site-packages/NetEase_MusicBox-0.2.4.2-py3.7.egg/NEMbox/menu.py", line 116, in __init__
  File "/Users/CocoChen/.pyenv/versions/3.7.0/lib/python3.7/site-packages/NetEase_MusicBox-0.2.4.2-py3.7.egg/NEMbox/storage.py", line 98, in load
  File "/Users/CocoChen/.pyenv/versions/3.7.0/lib/python3.7/site-packages/NetEase_MusicBox-0.2.4.2-py3.7.egg/NEMbox/storage.py", line 102, in check_version
KeyError: 'version'

删除掉.netease-musicbox后可以使用，听了几首歌，莫名其妙就报错了，然后每次播放歌曲都报错，信息如下（查看评论正常）：
Exception in thread Thread-1:
                             Traceback (most recent call last):
                                                                 File "/Users/CocoChen/.pyenv/versions/3.7.0/lib/python3.7/threading.py", line 917, in _bootstrap_inner
                                                     self.run()
                                                                 File "/Users/CocoChen/.pyenv/versions/3.7.0/lib/python3.7/threading.py", line 865, in run
                                        self._target(*self._args, **self._kwargs)
                                                                                   File "/Users/CocoChen/.pyenv/versions/3.7.0/lib/python3.7/site-packages/NetEase_MusicBox-0.2.4.2-py3.7.egg/NEMbox/player.py", line 112, in runInThread
                                                                                                                       new_url = NetEase().songs_detail_new_api([sid])[0]['url']
                                                            File "/Users/CocoChen/.pyenv/versions/3.7.0/lib/python3.7/site-packages/NetEase_MusicBox-0.2.4.2-py3.7.egg/NEMbox/api.py", line 565, in songs_detail_new_api
                                                                                                      result = json.loads(connection.text)
                      File "/Users/CocoChen/.pyenv/versions/3.7.0/lib/python3.7/json/__init__.py", line 348, in loads
                                                                                                                         return _default_decoder.decode(s)
                                      File "/Users/CocoChen/.pyenv/versions/3.7.0/lib/python3.7/json/decoder.py", line 337, in decode
                   obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                                                      File "/Users/CocoChen/.pyenv/versions/3.7.0/lib/python3.7/json/decoder.py", line 355, in raw_decode
                                                       raise JSONDecodeError("Expecting value", s, err.value) from None
 json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by RRRRRm** [comment]
类似的问题

Traceback (most recent call last):
  File "/usr/bin/musicbox", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3079, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 570, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 888, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 774, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'NetEase-MusicBox==0.2.5.2' distribution was not found and is required by the application

**Comment by darknessomi** [comment]
经审阅：该 issue 已过时、已在讨论中解答、或长期无有效跟进，先行关闭。如问题在现行版本仍存在，请重新提交并附上环境与复现步骤。
