### ISSUE TITLE
Distribution Not Found:  'pycryptodomex'

### ISSUE THREAD

**Issue by Isuru29** [darknessomi/musicbox#739]
C:\Users\Isuru\Documents\GitHub\netease-dl>musicbox
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python37-32\Scripts\musicbox-script.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pkg_resources\__init__.py", line 3098, in <module>
    @_call_aside
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pkg_resources\__init__.py", line 3082, in _call_aside
    f(*args, **kwargs)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pkg_resources\__init__.py", line 3111, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pkg_resources\__init__.py", line 573, in _build_master
    ws.require(__requires__)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pkg_resources\__init__.py", line 891, in require
    needed = self.resolve(parse_requirements(requirements))
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pkg_resources\__init__.py", line 777, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pycryptodomex' distribution was not found and is required by NetEase-MusicBox

**Comment by darknessomi** [comment]
经审阅：该 issue 已过时、已在讨论中解答、或长期无有效跟进，先行关闭。如问题在现行版本仍存在，请重新提交并附上环境与复现步骤。
