### ISSUE TITLE
Search song error

### ISSUE THREAD

**Issue by leewp14** [darknessomi/musicbox#740]
after perform a search, will return below error and exit. 
`Traceback (most recent call last):
  File "/home/leewp14/.local/lib/python2.7/site-packages/NEMbox/__main__.py", line 37, in start
    nembox_menu.start_fork(version)
  File "/home/leewp14/.local/lib/python2.7/site-packages/NEMbox/menu.py", line 223, in start_fork
    Menu().start()
  File "/home/leewp14/.local/lib/python2.7/site-packages/NEMbox/menu.py", line 314, in start
    self.dispatch_enter(idx)
  File "/home/leewp14/.local/lib/python2.7/site-packages/NEMbox/menu.py", line 743, in dispatch_enter
    self.datalist = self.search(self.datatype)
  File "/home/leewp14/.local/lib/python2.7/site-packages/NEMbox/menu.py", line 181, in search
    return self.api.dig_info(datalist, category)
  File "/home/leewp14/.local/lib/python2.7/site-packages/NEMbox/api.py", line 538, in dig_info
    return Parse.songs(data)
  File "/home/leewp14/.local/lib/python2.7/site-packages/NEMbox/api.py", line 152, in songs
    album_name, album_id = Parse.song_album(song)
  File "/home/leewp14/.local/lib/python2.7/site-packages/NEMbox/api.py", line 116, in song_album
    raise ValueError
ValueError
`
Ubuntu 16.04. non-root. with http-proxy.

**Comment by leewp14** [comment]
*added steps to reproduce as problem is only reproducible when searching certain terms

**Comment by jomainqaq** [comment]
The same reeor in Ubuntu 18.04
