### ISSUE TITLE
不支持Windows系统吗？

### ISSUE THREAD

**Issue by grant36x** [darknessomi/musicbox#747]
如题

**Comment by i042416** [comment]
启动报错：C:\Code\musicbox>musicbox
Traceback (most recent call last):
  File "C:\MyApp\py20180816\Scripts\musicbox-script.py", line 11, in <module>
    load_entry_point('NetEase-MusicBox==0.2.5.3', 'console_scripts', 'musicbox')()
  File "C:\MyApp\py20180816\lib\site-packages\netease_musicbox-0.2.5.3-py3.7.egg\NEMbox\__main__.py", line 35, in start
  File "C:\MyApp\py20180816\lib\site-packages\netease_musicbox-0.2.5.3-py3.7.egg\NEMbox\menu.py", line 112, in __init__
AttributeError: module 'signal' has no attribute 'SIGWINCH'

根据这篇[CSDN博客](https://blog.csdn.net/polyhedronx/article/details/81988335)的介绍，Windows不支持SIGWINCH.

**Comment by genzj** [comment]
我在尝试移植windows，有兴趣的话可以测试下：
https://github.com/genzj/musicbox/tree/win32

**Comment by zheisenberg** [comment]
> musicbox
Traceback (most recent call last):
  File "e:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "e:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "E:\Python27\Scripts\musicbox.exe\__main__.py", line 5, in <module>
  File "e:\python27\lib\site-packages\NEMbox\__main__.py", line 9, in <module>
    import curses
  File "e:\python27\lib\curses\__init__.py", line 15, in <module>
    from _curses import *
ImportError: No module named _curses

**Comment by genzj** [comment]
@zheisenberg 是用的master分支还是我仓库里的win32分支呢？我做了个初步移植，但是要从这个分支安装，安装方法在readme里的windows部分：
https://github.com/genzj/musicbox/tree/win32#windows%E5%AE%89%E8%A3%85

但是还是各种不稳定 😢 Windows实在是难搞，主要集中在mpg123的状态回报经常卡住，导致播放中途停止。

**Comment by zheisenberg** [comment]
:100:

**Comment by colemanlee** [comment]
> 启动报错：C:\Code\musicbox>musicbox
> Traceback (most recent call last):
> File "C:\MyApp\py20180816\Scripts\musicbox-script.py", line 11, in 
> load_entry_point('NetEase-MusicBox==0.2.5.3', 'console_scripts', 'musicbox')()
> File "C:\MyApp\py20180816\lib\site-packages\netease_musicbox-0.2.5.3-py3.7.egg\NEMbox__main__.py", line 35, in start
> File "C:\MyApp\py20180816\lib\site-packages\netease_musicbox-0.2.5.3-py3.7.egg\NEMbox\menu.py", line 112, in **init**
> AttributeError: module 'signal' has no attribute 'SIGWINCH'
> 
> 根据这篇[CSDN博客](https://blog.csdn.net/polyhedronx/article/details/81988335)的介绍，Windows不支持SIGWINCH.

我也是Windows 10，看来真的不支持了。

**Comment by qiufeihong2018** [comment]
幸亏先来看issue

**Comment by darknessomi** [comment]
MusicBox 为命令行客户端，不支持 Windows 原生运行，先行关闭。
