### ISSUE TITLE
ｕｂｕｎｂｔｕ下播放歌曲报错

### ISSUE THREAD

**Issue by liangyuanpeng** [darknessomi/musicbox#751]
错误日志如下
``
Exception in thread Thread-1:
                             Traceback (most recent call last):
                                                                 File "/usr/lib/python3.5/thre 作词 : 小寒/廖慧明/郭顶_bootstrap_inner
                  作曲 : 林倛玉/郭顶                      self.run()
                                                                      File "/usr/lib/python3.5/threading.py", line 862, in run
                                                  self._target(*self._args, **self._kwargs)
             File "/usr/local/lib/python3.5/dist-packages/NetEase_MusicBox-0.2.5.3-py3.5.egg/NEMbox/player.py", line 216, in run_mpg123
                                                           stderr=subprocess.PIPE
   File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
                                                                     restore_signals, start_new_session)
                          File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
                   raise child_exception_type(errno_num, err_msg)
                                                                 FileNotFoundError: [Errno 2] No such file or directory: 'mpg123'

``

桌面右上角弹出了正在播放ＸＸＸ歌曲

**Comment by kigawas** [comment]
https://github.com/darknessomi/musicbox#%E5%BF%85%E9%80%89

**Comment by CleverPuppy** [comment]
感觉是没有装mpg123

    sudo apt-get install mpg123
