### ISSUE TITLE
在Ubuntu下运行 ，播放，报错

### ISSUE THREAD

**Issue by hiekay** [darknessomi/musicbox#752]
Exception in thread Thread-1:
Traceback (most recent call last):  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner  self.run()             
File "/usr/lib/python2.7/threading.py", line 754, in run   self.__target(*self.__args, **self.__kwargs)
File "/usr/local/lib/python2.7/dist-packages/NEMbox/player.py", line 216, in run_mpg123    stderr=subprocess.PIPE                                                                            
File "/usr/lib/python2.7/subprocess.py", line 394, in __init__errread, errwrite)
File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child   raise child_exception   OSError: [Errno 20] 不是目录

**Comment by darknessomi** [comment]
经审阅：该 issue 已过时、已在讨论中解答、或长期无有效跟进，先行关闭。如问题在现行版本仍存在，请重新提交并附上环境与复现步骤。
