### ISSUE TITLE
無法播放

### ISSUE THREAD

**Issue by junyuewang** [darknessomi/musicbox#753]
Exception in thread Thread-1:
                                                                      Traceback (most recent call last):
                                                                                                          File "/usr/lib64/python2.7/threading.py", line 813, in __bootstrap_inner
                                                 self.run()
                                                             File "/usr/lib64/python2.7/threading.py", line 766, in run
                                                                                                                           self.__target(*self.__args, **self.__kwargs)
                                    File "build/bdist.linux-mips64/egg/NEMbox/player.py", line 216, in run_mpg123
                                                                                                                     stderr=subprocess.PIPE
        File "/usr/lib64/python2.7/subprocess.py", line 710, in __init__
                                                                            errread, errwrite)
                                                                                                File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
                                      raise child_exception
                                                           OSError: [Errno 2] 没有那个文件或目录

**Comment by junyuewang** [comment]
build/bdist.linux-mips64/目錄下爲空

**Comment by Setsuna-Kitahara** [comment]
mpg123没装？
`sudo apt install mpg123`

**Comment by darknessomi** [comment]
经审阅：该 issue 已过时、已在讨论中解答、或长期无有效跟进，先行关闭。如问题在现行版本仍存在，请重新提交并附上环境与复现步骤。
