### ISSUE TITLE
播放歌曲的时候会出现此报错

### ISSUE THREAD

**Issue by GitZinc** [darknessomi/musicbox#754]
Traceback (most recent call last):
        File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
                                                                                 self.run()
             File "/usr/lib/python3.6/threading.py", line 864, in run
                                                                         self._target(*self._args, **self._kwargs)
                                    File "/home/phantom/.local/lib/python3.6/site-packages/NEMbox/player.py", line 276, in download_song
                                                            self.cache.start_download()
         File "/home/phantom/.local/lib/python3.6/site-packages/NEMbox/cache.py", line 81, in start_download
                                new_url = NetEase().songs_url([song_id])[0]['url']
  IndexError: list index out of range

**Comment by GitZinc** [comment]
应该是缓存索引超出了范围，但是还不知道改哪

**Comment by GitZinc** [comment]
源码安装也存在此问题

**Comment by stfairy** [comment]
Duplicate of #767

**Comment by darknessomi** [comment]
与 #767 重复，先行关闭。
