### ISSUE TITLE
Bug反馈~搜索/播放/缓存/

### ISSUE THREAD

**Issue by carloswear** [darknessomi/musicbox#757]
树莓派上基于Debian的OSMC系统
Python 2.7.13

搜索：
歌曲名搜索的时候无论怎么搜都不会有结果，其他无问题（专辑/歌手等）

缓存：
一旦缓存就会报错，不过歌曲仍在后台播放：
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/__main__.py", line 37, in start
    nembox_menu.start_fork(version)
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/menu.py", line 223, in start_fork
    Menu().start()
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/menu.py", line 589, in start
    args=(s['song_id'], s['song_name'], s['artist'], s['mp3_url'])
TypeError: string indices must be integers

播放：
播放中的时候，如果切换列表，再播放其他的歌曲的话会出现同时播放两个音乐的情况~有时候甚至同时播放N个歌曲，诡异~

音频：
1，请问怎么更改mpg123的默认音频输出（系统默认HDMI，这个我可以强制全部输出到3.5mm接口，不过需要重启不方便我觉得）
2，有什么方法可以实现音频增强么？

另外，今天尝试用中文名字搜索国外乐队，比如“枪花”，竟然能直接搜索出“Guns& Roses”~神奇的功能！

**Comment by darknessomi** [comment]
经审阅：该 issue 已过时、已在讨论中解答、或长期无有效跟进，先行关闭。如问题在现行版本仍存在，请重新提交并附上环境与复现步骤。
