### ISSUE TITLE
windwos subsystem linux无法正常播放，还是说wsl本身就不能支持？

### ISSUE THREAD

**Issue by raoxiaoman** [darknessomi/musicbox#760]
我用windwos subsystem ubuntu 16.04 安装了musicbox 正常打开登入 但不能播放音乐 
报错信息：

**Comment by raoxiaoman** [comment]
Exception in thread Thread-1:
                             Traceback (most recent call last):
                                                                 File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
                                                                                                                                          self.run()
               File "/usr/lib/python3.5/threading.py", line 862, in run
                                                                           self._target(*self._args, **self._kwargs)
                                                                                                                      File "/usr/local/lib/python3.5/dist-packages/NetEase_MusicBox-0.2.5.3-py3.5.egg/NEMbox/player.py", line 251, in run_mpg123
                                                                                                             self.next()
                                                                                                                          File "/usr/local/lib/python3.5/dist-packages/NetEase_MusicBox-0.2.5.3-py3.5.egg/NEMbox/player.py", line 408, in next
                                                                                                           self.stop()
                                                                                                                        File "/usr/local/lib/python3.5/dist-packages/NetEase_MusicBox-0.2.5.3-py3.5.egg/NEMbox/player.py", line 178, in stop
                                                                                                         self.popen_handler.stdin.flush()
  BrokenPipeError: [Errno 32] Broken pipe

**Comment by kigawas** [comment]
mpg123不能在wsl里面用

**Comment by raoxiaoman** [comment]
所以wsl本身就不能支持musicbox，是吧？

**Comment by raoxiaoman** [comment]
好的
