### ISSUE TITLE
搜索报错

### ISSUE THREAD

**Issue by zhufengning** [darknessomi/musicbox#762]
```
Traceback (most recent call last):
  File "/home/zfn/.local/lib/python3.7/site-packages/NEMbox/__main__.py", line 37, in start
    nembox_menu.start_fork(version)
  File "/home/zfn/.local/lib/python3.7/site-packages/NEMbox/menu.py", line 223, in start_fork
    Menu().start()
  File "/home/zfn/.local/lib/python3.7/site-packages/NEMbox/menu.py", line 314, in start
    self.dispatch_enter(idx)
  File "/home/zfn/.local/lib/python3.7/site-packages/NEMbox/menu.py", line 743, in dispatch_enter
    self.datalist = self.search(self.datatype)
  File "/home/zfn/.local/lib/python3.7/site-packages/NEMbox/menu.py", line 181, in search
    return self.api.dig_info(datalist, category)
  File "/home/zfn/.local/lib/python3.7/site-packages/NEMbox/api.py", line 538, in dig_info
    return Parse.songs(data)
  File "/home/zfn/.local/lib/python3.7/site-packages/NEMbox/api.py", line 152, in songs
    album_name, album_id = Parse.song_album(song)
  File "/home/zfn/.local/lib/python3.7/site-packages/NEMbox/api.py", line 116, in song_album
    raise ValueError
ValueError
```

**Comment by darknessomi** [comment]
经审阅：该 issue 已过时、已在讨论中解答、或长期无有效跟进，先行关闭。如问题在现行版本仍存在，请重新提交并附上环境与复现步骤。
