### ISSUE TITLE
UnicodeDecodeError, can't  use keyboard

### ISSUE THREAD

**Issue by discretetimes** [darknessomi/musicbox#764]
System Platform | x86_64, Linux-4.18.16-200.fc28.x86_64-x86_64-with-fedora-28-Twenty_Eight
Terminal  :  gnome-terminal, xterm
musicbox version : NetEase_MusicBox-0.2.5.3-py3.6

Install method
[martin@fedora ~]$  proxychains4 pip install NetEase-MusicBox   --user
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/lib64/proxychains-ng/libproxychains4.so
[proxychains] DLL init: proxychains-ng 4.12
[proxychains] DLL init: proxychains-ng 4.12
Requirement already satisfied: NetEase-MusicBox in ./.local/lib/python2.7/site-packages
Requirement already satisfied: requests in /usr/lib/python2.7/site-packages (from NetEase-MusicBox)
Requirement already satisfied: BeautifulSoup4 in /usr/lib/python2.7/site-packages (from NetEase-MusicBox)
Requirement already satisfied: pycryptodomex in /usr/lib64/python2.7/site-packages (from NetEase-MusicBox)
Requirement already satisfied: future in /usr/lib/python2.7/site-packages (from NetEase-MusicBox)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python2.7/site-packages (from requests->NetEase-MusicBox)
Requirement already satisfied: idna<2.7,>=2.5 in /usr/lib/python2.7/site-packages (from requests->NetEase-MusicBox)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/lib/python2.7/site-packages (from requests->NetEase-MusicBox)

Logfile:
tail -f ~/.netease-musicbox/musicbox.log 
2018-11-02 17:40:07,515 - WARNING - NEMbox.osdlyrics:26: PyQt4 module not installed.
2018-11-02 17:40:07,515 - WARNING - NEMbox.osdlyrics:27: Osdlyrics Not Available.
2018-11-02 17:40:11,306 - DEBUG - NEMbox.player:285: 1313558861,我喜欢你,http://m10.music.126.net/20181020200808/e656a52a8af0941f87dc2ee0cb22f697/ymusic/41c2/583f/76d6/272a7073e97463fb7174c2d617a771b3.mp3

Error run
[martin@fedora ~]$ musicbox
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/NetEase_MusicBox-0.2.5.3-py3.6.egg/NEMbox/__main__.py", line 37, in start
    nembox_menu.start_fork(version)
  File "/usr/local/lib/python3.6/site-packages/NetEase_MusicBox-0.2.5.3-py3.6.egg/NEMbox/menu.py", line 221, in start_fork
    Menu().update_alert(version)
  File "/usr/local/lib/python3.6/site-packages/NetEase_MusicBox-0.2.5.3-py3.6.egg/NEM_ _ z Z Z LD 128k 你是年少的欢喜 - 王贰浪  < 你是年少的欢喜 >
    latest = Menu().check_version()
![screenshot from 2018-11-02 17-42-58](https://user-images.githubusercontent.com/32239426/47907721-bd8faa00-dec6-11e8-8317-a2884852b3d4.png)

  File "/usr/local/lib/python3.6/site-packages/NetEase_MusicBox-0.2.5.3-py3.6.egg/NEMbox/menu.py", line 213, in check_version
    data = self.api.get_version()
  File "/usr/local/lib/python3.6/site-packages/NetEase_MusicBox-0.2.5.3-py3.6.egg/NEMbox/api.py", line 515, in get_version
    return requests.get(action).json()
  File "/usr/lib/python3.6/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests_cache-0.4.13-py3.6.egg/requests_cache/core.py", line 126, in request
    **kwargs
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests_cache-0.4.13-py3.6.egg/requests_cache/core.py", line 97, in send
    response, timestamp = self.cache.get_response_and_time(cache_key)
  File "/usr/local/lib/python3.6/site-packages/requests_cache-0.4.13-py3.6.egg/requests_cache/backends/base.py", line 70, in get_response_and_time
    if key not in self.responses:
  File "/usr/lib64/python3.6/_collections_abc.py", line 666, in __contains__
    self[key]
  File "/usr/local/lib/python3.6/site-packages/requests_cache-0.4.13-py3.6.egg/requests_cache/backends/storage/dbdict.py", line 163, in __getitem__
    return pickle.loads(bytes(super(DbPickleDict, self).__getitem__(key)))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1: ordinal not in range(128)

可以使用 enter 键播放， 但是其他操作无效
![screenshot from 2018-11-02 17-58-52](https://user-images.githubusercontent.com/32239426/47908862-30018980-dec9-11e8-987c-99bbc797882c.png)

**Comment by darknessomi** [comment]
经审阅：该 issue 已过时、已在讨论中解答、或长期无有效跟进，先行关闭。如问题在现行版本仍存在，请重新提交并附上环境与复现步骤。
