### ISSUE TITLE
小白求教！运行musicbox后报错

### ISSUE THREAD

**Issue by Brannua** [darknessomi/musicbox#774]

**Comment by Brannua** [comment]
Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python37-32\Scripts\musicbox-script.py", line 11, in <module>
    load_entry_point('NetEase-MusicBox==0.2.5.4', 'console_scripts', 'musicbox')()
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pkg_resources\__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pkg_resources\__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pkg_resources\__init__.py", line 2324, in load
    return self.resolve()
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pkg_resources\__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python37-32\lib\site-packages\netease_musicbox-0.2.5.4-py3.7.egg\NEMbox\__main__.py", line 9, in <module>
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python37-32\lib\curses\__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'

**Comment by Brannua** [comment]
我是win10系统，已经clone并执行了steup.py install

**Comment by Brannua** [comment]
是还需要安装依赖么？如果是，那么怎么安装啊。。

**Comment by kigawas** [comment]
https://pypi.org/project/windows-curses/

Windows没有Linux自带的终端库curses，试一下这个

**Comment by Brannua** [comment]
恩嗯，我安装了，然后又执行了一下musicbox，结果Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python37-32\Scripts\musicbox-script.py", line 11, in <module>
    load_entry_point('NetEase-MusicBox==0.2.5.4', 'console_scripts', 'musicbox')()
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python37-32\lib\site-packages\netease_musicbox-0.2.5.4-py3.7.egg\NEMbox\__main__.py", line 35, in start
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python37-32\lib\site-packages\netease_musicbox-0.2.5.4-py3.7.egg\NEMbox\menu.py", line 112, in __init__
AttributeError: module 'signal' has no attribute 'SIGWINCH'
这又是什么问题。。

**Comment by starryhcy** [comment]
似乎是不支持win系统，你可以看一下前面的有个问题里面提到了，有人在分支做了移植，安装方法在readme里的windows部分：https://github.com/genzj/musicbox/tree/win32#windows安装 ，但是好像不稳定

**Comment by cupen** [comment]
windows 下何不用官方的 GUI 版？ 非要用也建议是 wsl/debian 。
