### ISSUE TITLE
树莓派musicbox报错

### ISSUE THREAD

**Issue by lianduy** [darknessomi/musicbox#775]
树莓派3+ 官方系统，启动musicbox时会打印一下错误：
File "/usr/lib/python3/dist-packages/urllib3/packages/ordered_dict.py", line 6, in <module> from thread import get_ident as _get_ident
ImportError: No module named 'thread'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/bin/musicbox", line 11, in <module>
sys.exit(start())
File "/usr/local/lib/python3.5/dist-packages/NEMbox/__main__.py", line 37, in start nembox_menu.start_fork(version)
File "/usr/local/lib/python3.5/dist-packages/NEMbox/menu.py", line 218, in start_fork Menu().update_alert(version)
File "/usr/local/lib/python3.5/dist-packages/NEMbox/menu.py", line 192, in update_alert latest = Menu().check_version()
File "/usr/local/lib/python3.5/dist-packages/NEMbox/menu.py", line 210, in check_version data = self.api.get_version()
File "/usr/local/lib/python3.5/dist-packages/NEMbox/api.py", line 561, in get_version return requests.get(action).json()
File "/usr/lib/python3/dist-packages/requests/api.py", line 70, in get return request('get', url, params=params, **kwargs)
File "/usr/lib/python3/dist-packages/requests/api.py", line 56, in request return session.request(method=method, url=url, **kwargs)
File "/usr/local/lib/python3.5/dist-packages/requests_cache/core.py", line 126, in request **kwargs
File "/usr/lib/python3/dist-packages/requests/sessions.py", line 488, in request resp = self.send(prep, **send_kwargs)
File "/usr/local/lib/python3.5/dist-packages/requests_cache/core.py", line 97, in send response, timestamp = self.cache.get_response_and_time(cache_key)
File "/usr/local/lib/python3.5/dist-packages/requests_cache/backends/base.py", line 70, in get_response_and_time if key not in self.responses:
File "/usr/lib/python3.5/_collections_abc.py", line 603, in __contains__ self[key]
File "/usr/local/lib/python3.5/dist-packages/requests_cache/backends/storage/dbdict.py", line 163, in __getitem__ return pickle.loads(bytes(super(DbPickleDict, self).__getitem__(key)))
File "/usr/lib/python3/dist-packages/urllib3/packages/ordered_dict.py", line 8, in <module> from dummy_thread import get_ident as _get_ident
ImportError: No module named 'dummy_thread'

**Comment by kigawas** [comment]
更新Python版本

**Comment by RunjiLiu** [comment]
问一下，为什么我输入musicbox找不到命令呢
