### ISSUE TITLE
archlinux报错

### ISSUE THREAD

**Issue by oubl23** [darknessomi/musicbox#78]
Traceback (most recent call last):
  File "/bin/musicbox", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3084, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3070, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3097, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 651, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 952, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 839, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'NetEase-MusicBox==0.1.5.6' distribution was not found and is required by the application

**Comment by oubl23** [comment]
已经解决 程序很棒

**Comment by oubl23** [comment]
我又有问题了，为什么每一栏只显示9个？

**Comment by oubl23** [comment]
我又懂是什么问题了，就当我是自娱自乐吧！
