### ISSUE TITLE
播放完一首后崩溃了

### ISSUE THREAD

**Issue by nickfan** [darknessomi/musicbox#792]
macos,python3

现象：播了一段时间以后，有一首歌结束后报错：

```python

Exception in thread Thread-137:
                               Traceback (most recent call last):
                                                                   File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
                                                                                    self.run()
                                                                                                File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run
                                                                                                    self._target(*self._args, **self._kwargs)
                  File "/usr/local/lib/python3.7/site-packages/NEMbox/player.py", line 234, in run_mpg123
                                                                                                             self.popen_handler.stdin.write(b'L ' + url.encode('utf-8') + b'\n')
                                                   AttributeError: 'NoneType' object has no attribute 'encode'
```
![image](https://user-images.githubusercontent.com/100613/53469586-75aa1980-3a99-11e9-86ec-7385735599e2.png)

**Comment by nickfan** [comment]
个人自己的歌单，播放模式随机。

**Comment by soonboylena** [comment]
我这理由相同的问题。 manjaro。
