### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by handsome-feng** [darknessomi/musicbox#802]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/NetEase_MusicBox-0.2.5.4-py3.7.egg/NEMbox/__main__.py", line 34, in start
    nembox_menu.start_fork(version)
  File "/usr/local/lib/python3.7/dist-packages/NetEase_MusicBox-0.2.5.4-py3.7.egg/NEMbox/menu.py", line 229, in start_fork
    Menu().update_alert(version)
  File "/usr/local/lib/python3.7/dist-packages/NetEase_MusicBox-0.2.5.4-py3.7.egg/NEMbox/menu.py", line 198, in update_alert
    latest = Menu().check_version()
  File "/usr/local/lib/python3.7/dist-packages/NetEase_MusicBox-0.2.5.4-py3.7.egg/NEMbox/menu.py", line 221, in check_version
    data = self.api.get_version()
  File "/usr/local/lib/python3.7/dist-packages/NetEase_MusicBox-0.2.5.4-py3.7.egg/NEMbox/api.py", line 556, in get_version
    return requests.get(action).json()
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests_cache-0.4.13-py3.7.egg/requests_cache/core.py", line 126, in request
    **kwargs
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests_cache-0.4.13-py3.7.egg/requests_cache/core.py", line 97, in send
    response, timestamp = self.cache.get_response_and_time(cache_key)
  File "/usr/local/lib/python3.7/dist-packages/requests_cache-0.4.13-py3.7.egg/requests_cache/backends/base.py", line 70, in get_response_and_time
    if key not in self.responses:
  File "/usr/lib/python3.7/_collections_abc.py", line 666, in __contains__
    self[key]
  File "/usr/local/lib/python3.7/dist-packages/requests_cache-0.4.13-py3.7.egg/requests_cache/backends/storage/dbdict.py", line 163, in __getitem__
    return pickle.loads(bytes(super(DbPickleDict, self).__getitem__(key)))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1: ordinal not in range(128)
```

**Comment by DanchuoZhong** [comment]
同样遇到了这个问题，使用的是git clone安装master环境，方法是：
> $ git clone https://github.com/darknessomi/musicbox.git && cd musicbox
$ python3 setup.py install
运行环境为Ubuntu 18.04.2

**Comment by yangxuanx** [comment]
相同问题

**Comment by yangxuanx** [comment]
系统已更换为archlinux，发现archlinuxcn 源下的musicbox安装后出现相同问题，解决方法是，删除主目录下的.netease-musicbox文件夹，重新启动即可

**Comment by kigawas** [comment]
`export PYTHONIOENCODING=utf-8`试一下？

**Comment by darknessomi** [comment]
经审阅：该 issue 已过时、已在讨论中解答、或长期无有效跟进，先行关闭。如问题在现行版本仍存在，请重新提交并附上环境与复现步骤。
