### ISSUE TITLE
在没有播放歌曲的时候按下ｉ回导致程序崩溃

### ISSUE THREAD

**Issue by Lovestarni** [darknessomi/musicbox#803]
Traceback (most recent call last):
  File "/home/skywalker/anaconda3/lib/python3.6/site-packages/NEMbox/__main__.py", line 37, in start
    nembox_menu.start_fork(version)
  File "/home/skywalker/anaconda3/lib/python3.6/site-packages/NEMbox/menu.py", line 220, in start_fork
    Menu().start()
  File "/home/skywalker/anaconda3/lib/python3.6/site-packages/NEMbox/menu.py", line 593, in start
    if self.player.playing_id != -1:
  File "/home/skywalker/anaconda3/lib/python3.6/site-packages/NEMbox/player.py", line 121, in playing_id
    return self.current_song['song_id']
KeyError: 'song_id'

**Comment by Lovestarni** [comment]
感觉少一个键的空值错误判断

**Comment by younger-1** [comment]
> Traceback (most recent call last):
> File "/home/skywalker/anaconda3/lib/python3.6/site-packages/NEMbox/**main**.py", line 37, in start
> nembox_menu.start_fork(version)
> File "/home/skywalker/anaconda3/lib/python3.6/site-packages/NEMbox/menu.py", line 220, in start_fork
> Menu().start()
> File "/home/skywalker/anaconda3/lib/python3.6/site-packages/NEMbox/menu.py", line 593, in start
> if self.player.playing_id != -1:
> File "/home/skywalker/anaconda3/lib/python3.6/site-packages/NEMbox/player.py", line 121, in playing_id
> return self.current_song['song_id']
> KeyError: 'song_id'

进入界面后按下 i都会出现一样的错误信息

**Comment by darknessomi** [comment]
已在 #974 中修复。

**原因：**
1. 旧版 `Player.playing_id` 直接访问 `current_song['song_id']`，无歌曲时 KeyError（已在 #858 改为 `.get()`）
2. 菜单用 `playing_id != -1` 判断，但无歌曲时 `playing_id` 为 `None`，条件仍为真，会打开 `song?id=None`

**修复：** 将判断改为 `playing_id is not None`。

请更新到最新 master 后验证。
