### ISSUE TITLE
Bug  按 = 加音量时报错

### ISSUE THREAD

**Issue by WilenceYao** [darknessomi/musicbox#81]
测试环境  openSuse 13.2 Python 2.7.8

错误信息 

        Traceback (most recent call last):                                                                                                                                      

        File "/usr/lib/python2.7/site-packages/NetEase_MusicBox-0.1.5.6-py2.7.egg/NEMbox/__init__.py", line 15, in start 
        nembox_menu.start()
                                                                                                                      
        File "/usr/lib/python2.7/site-packages/NetEase_MusicBox-0.1.5.6-py2.7.egg/NEMbox/menu.py", line 241, in start                                                         
        self.player.volume_up()                                                                                                                          

        File "/usr/lib/python2.7/site-packages/NetEase_MusicBox-0.1.5.6-py2.7.egg/NEMbox/player.py", line 162, in volume_up
            self.popen_handler.stdin.write("V " + str(self.volume) + "\n")
        IOError: [Errno 32] Broken pipe

查看代码，这一行代码为

    def volume_up(self):
            self.volume = self.volume + 7
            if (self.volume > 100):
                self.volume = 100
            self.popen_handler.stdin.write("V " + str(self.volume) + "\n")

猜测原因：可能是对相关的设备的声卡支持不完整

**Comment by Catofes** [comment]
应该是在增加音量的时候碰巧碰到了切歌，所以broken pipe。
