### ISSUE TITLE
树莓派无法登录

### ISSUE THREAD

**Issue by lianduy** [darknessomi/musicbox#810]
树莓派无法登录

**Comment by lianduy** [comment]
使用sudo pip3 install NetEase-MusicBox的最新的包

**Comment by lianduy** [comment]
使用git安装登录后，报下面的错误

Traceback (most recent call last):
File "/usr/local/bin/musicbox", line 11, in <module> load_entry_point('NetEase-MusicBox==0.2.5.4', 'console_scripts', 'musicbox')()
File "/usr/local/lib/python3.5/dist-packages/NetEase_MusicBox-0.2.5.4-py3.5.egg/NEMbox/__main__.py", line 34, in start
File "/usr/local/lib/python3.5/dist-packages/NetEase_MusicBox-0.2.5.4-py3.5.egg/NEMbox/menu.py", line 231, in start_fork
File "/usr/local/lib/python3.5/dist-packages/NetEase_MusicBox-0.2.5.4-py3.5.egg/NEMbox/menu.py", line 369, in start
File "/usr/local/lib/python3.5/dist-packages/NetEase_MusicBox-0.2.5.4-py3.5.egg/NEMbox/menu.py", line 670, in dispatch_enter
File "/usr/local/lib/python3.5/dist-packages/NetEase_MusicBox-0.2.5.4-py3.5.egg/NEMbox/menu.py", line 880, in choice_channel
File "/usr/local/lib/python3.5/dist-packages/NetEase_MusicBox-0.2.5.4-py3.5.egg/NEMbox/menu.py", line 835, in request_api
File "/usr/local/lib/python3.5/dist-packages/NetEase_MusicBox-0.2.5.4-py3.5.egg/NEMbox/menu.py", line 151, in login
                                                                                                                                     File "/usr/local/lib/python3.5/dist-packages/NetEase_MusicBox-0.2.5.4-py3.5.egg/NEMbox/api.py", line 394, in login
File "/usr/lib/python3.5/http/cookiejar.py", line 1880, in save
                                                                                                                                          f.write(self.as_lwp_str(ignore_discard, ignore_expires))
File "/usr/lib/python3.5/http/cookiejar.py", line 1867, in as_lwp_strr.append("Set-Cookie3: %s" % lwp_cookie_str(cookie))
File "/usr/lib/python3.5/http/cookiejar.py", line 1833, in lwp_cookie_strkeys = sorted(cookie._rest.keys())
 AttributeError: 'NoneType' object has no attribute 'keys'

**Comment by redchenjs** [comment]
是不是开启了登录保护的原因

**Comment by Rigil-Kentaurus** [comment]
我也遇到了类似问题……求解

**Comment by ranio** [comment]
OSX 10.14.4无法登录，"登录信息好像不对"。

**Comment by updater1234** [comment]
linuxmint19.1上也有同样的问题。

**Comment by YogiLiu** [comment]
Arch Linux上遇到了同样地问题

**Comment by gary02** [comment]
ubuntu16.04 同

**Comment by machsix** [comment]
同样问题，手机没有绑定，自然也没有登陆保护，网页可以登陆

**Comment by pilgrimaz** [comment]
这个问题解决了吗  我直接输入musicbox就报错了
