### ISSUE TITLE
No module named '_curses'

### ISSUE THREAD

**Issue by lovecn** [darknessomi/musicbox#815]
```js
λ musicbox
Traceback (most recent call last):
  File "d:\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\python\Scripts\musicbox.exe\__main__.py", line 5, in <module>
  File "d:\python\lib\site-packages\NEMbox\__main__.py", line 9, in <module>
    import curses
  File "d:\python\lib\curses\__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'
```

**Comment by freezing1988** [comment]
同样的问题

**Comment by darknessomi** [comment]
经审阅：该 issue 已过时、已在讨论中解答、或长期无有效跟进，先行关闭。如问题在现行版本仍存在，请重新提交并附上环境与复现步骤。
