### ISSUE TITLE
pkg_resources.DistributionNotFound: The 'requests-cache' distribution was not found and is required by NetEase-MusicBox

### ISSUE THREAD

**Issue by tienflow** [darknessomi/musicbox#818]
Traceback (most recent call last):
  File "/usr/bin/musicbox", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3241, in <module>
    @_call_aside
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3225, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3254, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'requests-cache' distribution was not found and is required by NetEase-MusicBox

**Comment by axionl** [comment]
For the users of archlinuxcn repo, I re-added this package, which was removed during the previous cleanup. However, there may be other design issues with its cookies mechanism and need to be fixed.

**Comment by kigawas** [comment]
please try using `pip` or `git clone`

**Comment by darknessomi** [comment]
经审阅：该 issue 已过时、已在讨论中解答、或长期无有效跟进，先行关闭。如问题在现行版本仍存在，请重新提交并附上环境与复现步骤。
