### ISSUE TITLE
播放音乐报错！

### ISSUE THREAD

**Issue by avakpan** [darknessomi/musicbox#82]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/NetEase_MusicBox-0.1.5.6-py2.7.egg/NEMbox/__init__.py", line 15, in start
    nembox_menu.start()
  File "/usr/local/lib/python2.7/dist-packages/NetEase_MusicBox-0.1.5.6-py2.7.egg/NEMbox/menu.py", line 262, in start
    self.player.play(datatype, datalist, idx)
  File "/usr/local/lib/python2.7/dist-packages/NetEase_MusicBox-0.1.5.6-py2.7.egg/NEMbox/player.py", line 90, in play
    self.pause()
  File "/usr/local/lib/python2.7/dist-packages/NetEase_MusicBox-0.1.5.6-py2.7.egg/NEMbox/player.py", line 129, in pause
    os.kill(self.popen_handler.pid, signal.SIGSTOP)
AttributeError: 'NoneType' object has no attribute 'pid'

**Comment by mfk530** [comment]
安装mpg123
sudo apt-get install mpg123
