### ISSUE TITLE
python3.7 登录不正常

### ISSUE THREAD

**Issue by cupen** [darknessomi/musicbox#824]
我本地代码来自 master 分支，版本号我自己改的 `0.2.5.5`，可忽略。

                                               请输入登录信息(支持手机登录)

                                               账号: xxxx@xxx.xx
                                               密码:

```
Traceback (most recent call last):
File "/home/cupen/.local/bin/musicbox", line 11, in <module>load_entry_point('NetEaseMusicBox==0.2.5.5', 'console_scripts', 'musicbox')()
File "/home/cupen/.local/lib/python3.7/site-packages/NetEase_MusicBox-0.2.5.5py3.7.egg/NEMbox/__main__.py", line 34, in start
File "/home/cupen/.local/lib/python3.7/site-packages/NetEase_MusicBox-0.2.5.5-py3.7.egg/NEMbox/menu.py", line 231, in start_fork
File "/home/cupen/.local/lib/python3.7/site-packages/NetEase_MusicBox-0.2.5.5-py3.7.egg/NEMbox/menu.py", line 369, in start
File "/home/cupen/.local/lib/python3.7/site-packages/NetEase_MusicBox-0.2.5.5-py3.7.egg/NEMbox/menu.py", line 670, in dispatch_enter
File "/home/cupen/.local/lib/python3.7/site-packages/NetEase_MusicBox-0.2.5.5-py3.7.egg/NEMbox/menu.py", line 880, in choice_channel
File "/home/cupen/.local/lib/python3.7/site-packages/NetEase_MusicBox-0.2.5.5-py3.7.egg/NEMbox/menu.py", line 835, in request_api
File "/home/cupen/.local/lib/python3.7/site-packages/NetEase_MusicBox-0.2.5.5-py3.7.egg/NEMbox/menu.py", line 151, in login
File "/home/cupen/.local/lib/python3.7/site-packages/NetEase_MusicBox-0.2.5.5-py3.7.egg/NEMbox/api.py", line 394, in login
File "/usr/lib/python3.7/http/cookiejar.py", line 1890, in save
    f.write(self.as_lwp_str(ignore_discard, ignore_expires))
File "/usr/lib/python3.7/http/cookiejar.py", line 1877, in as_lwp_str
    r.append("Set-Cookie3: %s" % lwp_cookie_str(cookie))
File "/usr/lib/python3.7/http/cookiejar.py", line 1843, in lwp_cookie_str
    keys = sorted(cookie._rest.keys())
AttributeError: 'NoneType' object has no attribute 'keys'
```

**Comment by cupen** [comment]
看起来是系统库里的代码，暂时不知道为毛。
