### ISSUE TITLE
ui类型错误?直接显示版权问题无法播放

### ISSUE THREAD

**Issue by startnoob** [darknessomi/musicbox#830]
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/NEMbox/__main__.py", line 34, in start
    nembox_menu.start_fork(version)
  File "/usr/lib/python3.7/site-packages/NEMbox/menu.py", line 231, in start_fork
    Menu().start()
  File "/usr/lib/python3.7/site-packages/NEMbox/menu.py", line 280, in start
    self.player.update_size()
  File "/usr/lib/python3.7/site-packages/NEMbox/player.py", line 514, in update_size
    self.build_playinfo()
  File "/usr/lib/python3.7/site-packages/NEMbox/player.py", line 166, in build_playinfo
    pause=not self.playing_flag,
  File "/usr/lib/python3.7/site-packages/NEMbox/ui.py", line 112, in build_playinfo
    song_name + self.space + artist + "  < " + album_name + " >",
TypeError: can only concatenate str (not "NoneType") to str

**Comment by isdotjim** [comment]
搭个车...
想邀请Repo参与者来w3c.group创建项目的对应小组。w3c.group是类似知识星球的社群工具，小组可设置为付费且有赞助功能，同时也是一个区块链主导的创作者社区。这是相关介绍：
http://t.cn/Ai1vLcCU
http://t.cn/Ai1vLcCG
http://t.cn/Ai1vLcCA

**Comment by darknessomi** [comment]
经审阅：该 issue 已过时、已在讨论中解答、或长期无有效跟进，先行关闭。如问题在现行版本仍存在，请重新提交并附上环境与复现步骤。
