### ISSUE TITLE
播放报错 哈哈

### ISSUE THREAD

**Issue by wffeige** [darknessomi/musicbox#837]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/NEMbox/__main__.py", line 37, in start
    nembox_menu.start_fork(version)
  File "/usr/lib/python2.7/site-packages/NEMbox/menu.py", line 220, in start_fork
    Menu().start()
  File "/usr/lib/python2.7/site-packages/NEMbox/menu.py", line 391, in start
    self.player.playing_id)
  File "/usr/lib/python2.7/site-packages/NEMbox/player.py", line 121, in playing_id
    return self.current_song['song_id']
KeyError: u'song_id'

**Comment by darknessomi** [comment]
经审阅：该 issue 已过时、已在讨论中解答、或长期无有效跟进，先行关闭。如问题在现行版本仍存在，请重新提交并附上环境与复现步骤。
