### ISSUE TITLE
Arch linux(arm 版本) 无法运行

### ISSUE THREAD

**Issue by roleyzhang** [darknessomi/musicbox#84]
报错如下：
menu已经通过pip安装成功
$ musicbox
Traceback (most recent call last):
  File "/bin/musicbox", line 9, in <module>
    load_entry_point('NetEase-MusicBox==0.1.5.6', 'console_scripts', 'musicbox')()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.4/site-packages/NetEase_MusicBox-0.1.5.6-py3.4.egg/NEMbox/__init__.py", line 9, in <module>
    from menu import Menu
ImportError: cannot import name 'Menu'

**Comment by darknessomi** [comment]
请使用 Python 2.7 版本:-D

**Comment by roleyzhang** [comment]
谢谢、回头测试一下。python的向下兼容还真是问题

**Comment by roleyzhang** [comment]
故障排除，就是cpu占用率高，Python通病，不苛求了
