### ISSUE TITLE
播放音乐出现 BrokenPipeError

### ISSUE THREAD

**Issue by tanjuntao** [darknessomi/musicbox#841]
您好，我的系统是 Ubuntu 18.04 LTS，安装完 musicbox 和 mpg123 之后，输入账号密码能正常登陆，但是按下 `空格键` 播放歌曲时，出现以下错误：
```
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/NEMbox/__main__.py", line 37, in start
    nembox_menu.start_fork(version)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/NEMbox/menu.py", line 220, in start_fork
    Menu().start()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/NEMbox/menu.py", line 430, in start
    self.player.play_or_pause(idx, self.at_playing_list)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/NEMbox/player.py", line 374, in play_or_pause
    self.switch()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/NEMbox/player.py", line 220, in switch
    self.popen_handler.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe
```
望解答。

**Comment by wangjianyuan10** [comment]
这个是子进程管道崩溃,请参考我的fork版本 https://github.com/wangjianyuan10/musicbox
