### ISSUE TITLE
用termux安得Ubuntu播放错误

### ISSUE THREAD

**Issue by Victor9578** [darknessomi/musicbox#855]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/NetEase_MusicBox-0.2.5.4-py3.6.egg/NEMbox/__main__.py", line 34, in start
    nembox_menu.start_fork(version)
  File "/usr/local/lib/python3.6/dist-packages/NetEase_MusicBox-0.2.5.4-py3.6.egg/NEMbox/menu.py", line 231, in start_fork
    Menu().start()
  File "/usr/local/lib/python3.6/dist-packages/NetEase_MusicBox-0.2.5.4-py3.6.egg/NEMbox/menu.py", line 456, in start
    self.player.play_or_pause(idx, self.at_playing_list)
  File "/usr/local/lib/python3.6/dist-packages/NetEase_MusicBox-0.2.5.4-py3.6.egg/NEMbox/player.py", line 398, in play_or_pause
    self.stop()
  File "/usr/local/lib/python3.6/dist-packages/NetEase_MusicBox-0.2.5.4-py3.6.egg/NEMbox/player.py", line 197, in stop
    self.popen_handler.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe

**Comment by darknessomi** [comment]
经审阅：该 issue 已过时、已在讨论中解答、或长期无有效跟进，先行关闭。如问题在现行版本仍存在，请重新提交并附上环境与复现步骤。
