### ISSUE TITLE
archlinux kde 和 i3 下的问题

### ISSUE THREAD

**Issue by goodchengwang** [darknessomi/musicbox#861]
Traceback (most recent call last):
  File "/usr/bin/musicbox", line 33, in <module>
    sys.exit(load_entry_point('NetEase-MusicBox==0.2.5.4', 'console_scripts', 'musicbox')())
  File "/usr/bin/musicbox", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.8/site-packages/NEMbox/__main__.py", line 14, in <module>
    from .menu import Menu
  File "/usr/lib/python3.8/site-packages/NEMbox/menu.py", line 27, in <module>
    from fuzzywuzzy import process
ModuleNotFoundError: No module named 'fuzzywuzzy'

**Comment by darknessomi** [comment]
经审阅：该 issue 已过时、已在讨论中解答、或长期无有效跟进，先行关闭。如问题在现行版本仍存在，请重新提交并附上环境与复现步骤。
