### ISSUE TITLE
manjaro 下的最新版启动报错问题

### ISSUE THREAD

**Issue by ryp1987** [darknessomi/musicbox#866]
Traceback (most recent call last):
  File "/usr/bin/musicbox", line 33, in <module>
    sys.exit(load_entry_point('NetEase-MusicBox==0.2.5.4', 'console_scripts', 'musicbox')())
  File "/usr/bin/musicbox", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.8/site-packages/NEMbox/__main__.py", line 14, in <module>
    from .menu import Menu
  File "/usr/lib/python3.8/site-packages/NEMbox/menu.py", line 37, in <module>
    from .cmd_parser import parse_keylist, cmd_parser, erase_coroutine
  File "/usr/lib/python3.8/site-packages/NEMbox/cmd_parser.py", line 18, in <module>
    **keyMap = Config().get("keymap")
  File "/usr/lib/python3.8/site-packages/NEMbox/config.py", line 234, in get
    if key not in self.config[name]["value"].keys():
KeyError: 'keymap'**

**Comment by baizeyv** [comment]
我在arch下也是这样，看报错是这个字典读不出来

**Comment by Me7426** [comment]
删除`~/.netease-musicbox/config.json`即可启动
看了下貌似是因为配置文件添加新字段了

**Comment by bily-goat** [comment]
好像要下一个python包
pip install -U --upgrade-strategy=eager requests-cache
作者已经有回答了 #915
