### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by ImFyatto** [darknessomi/musicbox#872]
## 运行环境

-  操作系统：ubuntu20.04LTS 内核：5.4.0-47
-  终端：xfce4-terminal 0.8.9.1 (Xfce 4.14)且运行tmux 3.0a
- Python版本：python3.8.2
- musicbox版本：version:0.2.5.4
- 安装方式：pip3
- 代理：无（在国内）

## 问题复现

musicbox -> 我的歌单 -> 输入帐号密码后提示“登录信息不对”

## 附加：

多次尝试删除~/.netease-musicbox/

**Comment by kigawas** [comment]
试一下master

**Comment by hehh2001** [comment]
archlinux   一样也是无法登录了

**Comment by MiraculousMoon** [comment]
manjaro同无法登录

**Comment by ImFyatto** [comment]
@kigawas 疯狂怀疑是网易云的api挂了

**Comment by kekemuyu** [comment]
树莓派也无法登录

**Comment by liboyang0112** [comment]
centos7也是

**Comment by wangbar0133** [comment]
怎么输入密码

**Comment by MiraculousMoon** [comment]
同样的问题在iease-music也有

**Comment by pkumza** [comment]
macbook 也登陆失败了

**Comment by XiaoMochou** [comment]
+1 今天刚发现这个问题。

**Comment by beGirt** [comment]
NetEase-MusicBox 0.2.5.4
Manjaro这个版本已经挺多天登录不上了,望修补

**Comment by zhangwenxuan322** [comment]
POST http://music.163.com/weapi/login/cellphone
Response Body:
```
{
  "message": "当前登录失败，请稍后再试",
  "code": 250
}
```
有时输完密码还会报错:
```
Exception ignored in: <module 'threading' from '/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py'>
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 1388, in _shutdown
    lock.acquire()
  File "/usr/local/lib/python3.8/site-packages/NEMbox/menu.py", line 189, in send_kill
    sys.exit()
SystemExit:
```

**Comment by zhangwenxuan322** [comment]
#876 已提交pr解决手机登录问题，手动添加一行即可解决问题，合并前各位可以手动改一下解决。

**Comment by i0Ek3** [comment]
@zhangwenxuan322  自己编译最新的master后，0.3.0版本，Mac(10.15.7)依然无法登录，还是显示 艾玛，登录信息好像不对呢 (O_O)#，无论是手机还是邮箱，Python3.8.6的版本，不清楚问题出在了哪里，还是说我操作有误？

**Comment by zhangwenxuan322** [comment]
@i0Ek3 抱歉，之前提pr的时候没注意，`countrycode='86'`的属性加到了邮箱登录判断下，而这应该在手机登录判断下，我需要重新提一下，谢谢反馈。

**Comment by zhangwenxuan322** [comment]
@i0Ek3 已合并master

**Comment by i0Ek3** [comment]
@zhangwenxuan322 ok我重新编译下试试。

**Comment by updater1234** [comment]
请问，怎么输入密码

**Comment by MiraculousMoon** [comment]
无法登录的问题继续出现
版本：0.2.5.4/0.3.0（分别来自archlinuxcn和源代码自己编译）

**Comment by attenuation** [comment]
接口已经大改，整个api接口可能需要重构
https://github.com/Binaryify/NeteaseCloudMusicApi/blob/master/module/login.js

**Comment by QRQaccount** [comment]
从pip3更新0.30版本后仍然无法登陆。会显示`信息不对`。
系统：Kubuntu20.04

**Comment by muzilong** [comment]
arch linux 同无法登陆。

**Comment by Brannua** [comment]
请问登陆时是否是输入账号后，按下 tab 键聚焦密码输入行？如果是这样的话，账号输入了手机号，密码输入后回车会提示信息不对，我的是（x86_64 Linux 5.9.8-2-MANJARO      Manjaro 20.2 Nibia      KDE 5.76.0 / Plasma 5.20.3）

**Comment by Brannua** [comment]
> 请问登陆时是否是输入账号后，按下 tab 键聚焦密码输入行？如果是这样的话，账号输入了手机号，密码输入后回车会提示信息不对，我的是（x86_64 Linux 5.9.8-2-MANJARO Manjaro 20.2 Nibia KDE 5.76.0 / Plasma 5.20.3）

同样的账号和密码在网易云音乐客户端登陆成功哈

**Comment by nnnewb** [comment]
https://github.com/darknessomi/musicbox/blob/5aadfb6f9ea7b5414a9a0acd9487f5be03183a7b/NEMbox/api.py#L393

试试加入 `custom_cookie={"os": "pc"}`

自己测了下，修改前返回 code=250 当前登录失败，请稍后再试
修改后正常，在 cookies.save 报错

https://github.com/nnnewb/musicbox/blob/5aadfb6f9ea7b5414a9a0acd9487f5be03183a7b/NEMbox/api.py#L346

py3 兼容的问题，改成 `rest={}` 恢复正常

**Comment by tempso** [comment]
macOS High Sierra,10.13.6, 仍旧无法登录，非常不方便，请求更新，谢谢。

**Comment by x93008** [comment]
输入密码是什么都没有显示吗？建议加上*号，否则我不知道自己有没有在输入
