### ISSUE TITLE
树莓派安装的ubuntu无法播放和登录

### ISSUE THREAD

**Issue by Qa7060123** [darknessomi/musicbox#873]
Exception in thread Thread-1:
Traceback (most recent call last):
 File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
self.run()
File "/usr/lib/python3.6/threading.py", line 864, in run
 self._target(*self._args, **self._kwargs)
File "/home/ubuntu/.local/lib/python3.6/site-packages/NEMbox/player.py", line 274, in run_mpg123
self.next()
File "/home/ubuntu/.local/lib/python3.6/site-packages/NEMbox/player.py", line 433, in next
self.stop()
 File "/home/ubuntu/.local/lib/python3.6/site-packages/NEMbox/player.py", line 192, in stop
self.popen_handler.stdin.flush()
BrokenPipeError: [Errno 32] 断开的管道

重装了mpg123和删除了.netease-musicbox里面的文件都不行

**Comment by darknessomi** [comment]
经审阅：该 issue 已过时、已在讨论中解答、或长期无有效跟进，先行关闭。如问题在现行版本仍存在，请重新提交并附上环境与复现步骤。
