### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by sonichy** [darknessomi/musicbox#875]
musicbox
Traceback (most recent call last):                                                                                                                                                             
  File "/usr/local/bin/musicbox", line 11, in <module>                                                                                                                                         
    load_entry_point('NetEase-MusicBox==0.2.5.4', 'console_scripts', 'musicbox')()                                                                                                             
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point                                                                                             
    return get_distribution(dist).load_entry_point(group, name)                                                                                                                                
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2793, in load_entry_point                                                                                            
    return ep.load()                                                                                                                                                                           
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2411, in load                                                                                                        
    return self.resolve()                                                                                                                                                                      
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2417, in resolve                                                                                                     
    module = __import__(self.module_name, fromlist=['__name__'], level=0)                                                                                                                      
  File "build/bdist.linux-x86_64/egg/NEMbox/__main__.py", line 14, in <module>                                                                                                                 
  File "/usr/local/lib/python2.7/dist-packages/NetEase_MusicBox-0.2.5.4-py2.7.egg/NEMbox/menu.py", line 921                                                                                    
    self.datatype, self.title, self.datalist, *_ = self.stack[0]                                                                                                                               
                                              ^                                                                                                                                                
SyntaxError: invalid syntax

**Comment by NibaZShab** [comment]
+1，同样错误，系统是manjaro20

**Comment by kigawas** [comment]
建议换到Python3
