### ISSUE TITLE
在使用搜索功能搜索中文名歌曲时出现问题

### ISSUE THREAD

**Issue by QRQaccount** [darknessomi/musicbox#908]
系统：Fedora 33
python版本：3.9
musicbox版本：使用pip安装的最新版

问题描述：直接输入中文搜索歌曲专辑等没有问题，但若搜索时打错字使用backspace键删除错字后再重新输入并查询时就会报错

主要报错信息如下
```
Traceback (most recent call last):
  File "/home/qrq/.local/lib/python3.9/site-packages/NEMbox/__main__.py", line 35, in start
    nembox_menu.start_fork(version)
  File "/home/qrq/.local/lib/python3.9/site-packages/NEMbox/menu.py", line 293, in start_fork
    Menu().start()
  File "/home/qrq/.local/lib/python3.9/site-packages/NEMbox/menu.py", line 709, in start
    self.enter_page_event()
  File "/home/qrq/.local/lib/python3.9/site-packages/NEMbox/menu.py", line 428, in enter_page_event
    self.dispatch_enter(idx)
  File "/home/qrq/.local/lib/python3.9/site-packages/NEMbox/menu.py", line 1121, in dispatch_enter
    self.datalist = self.search(self.datatype)
  File "/home/qrq/.local/lib/python3.9/site-packages/NEMbox/menu.py", line 235, in search
    keyword = self.ui.get_param(prompt)
  File "/home/qrq/.local/lib/python3.9/site-packages/NEMbox/ui.py", line 771, in get_param
    return keyword.decode("utf-8").strip()
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 3-4: invalid continuation byte
```

**Comment by darknessomi** [comment]
已在 #973 中修复。

**原因：** 搜索框使用 `getstr()` 按字节读取输入，Backspace 可能只删掉 UTF-8 多字节字符的一部分，导致 `keyword.decode("utf-8")` 抛出 `UnicodeDecodeError`。

**修复：**
- 优先使用 `get_wch()` 按字符输入，Backspace 整字删除
- 不支持 `get_wch` 的终端 fallback 到 `getstr()`，并用 `decode_terminal_input(..., errors="ignore")` 忽略无效字节

请更新到最新 master 后验证。
