### ISSUE TITLE
求帮忙看下，用手机termux和windows都报错

### ISSUE THREAD

**Issue by xp12047** [darknessomi/musicbox#914]
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/musicbox", line 8, in <module>
    sys.exit(start())
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/src/__init__.py", line 11, in start
    Menu().start()
AttributeError: 'Menu' object has no attribute 'start'

**Comment by arbaleast** [comment]
同问

**Comment by PRO-2684** [comment]
不支持，查看#911
