### ISSUE TITLE
播放时会出现一个时间转换错误

### ISSUE THREAD

**Issue by Duelist-Fiora** [darknessomi/musicbox#936]
错误信息
```
➜  ~ musicbox
Traceback (most recent call last):
  File "/home/l/.local/lib/python3.9/site-packages/NEMbox/__main__.py", line 35, in start
    nembox_menu.start_fork(version)
  File "/home/l/.local/lib/python3.9/site-packages/NEMbox/menu.py", line 293, in start_fork
    Menu().start()
  File "/home/l/.local/lib/python3.9/site-packages/NEMbox/menu.py", line 974, in start
    self.build_menu_processbar()
  File "/home/l/.local/lib/python3.9/site-packages/NEMbox/menu.py", line 545, in build_menu_processbar
    self.ui.build_process_bar(
  File "/home/l/.local/lib/python3.9/site-packages/NEMbox/ui.py", line 320, in build_process_bar
    self.update_lyrics(now_playing, lyrics, tlyrics)
  File "/home/l/.local/lib/python3.9/site-packages/NEMbox/ui.py", line 224, in update_lyrics
    next_lyric_time = get_lyric_time(lyrics[self.now_lyric_index + 1])
  File "/home/l/.local/lib/python3.9/site-packages/NEMbox/ui.py", line 197, in get_lyric_time
    datetime.datetime.strptime(get_timestap(lyric_line), "%M:%S.%f")
  File "/usr/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '99:00.00' does not match format '%M:%S.%f'
```

软件信息
```
➜  ~ musicbox -v
NetEase-MusicBox installed version:0.3.1

➜  ~ python -V
Python 3.9.7
```

系统信息
manjaro , 5.15内核

**Comment by rsp4jack** [comment]
仍未修复。
参见https://github.com/darknessomi/musicbox/blob/592e13d1b948201447d008f4f3e249d347f47f21/NEMbox/ui.py#L206
