### ISSUE TITLE
KeyError: 'song_id'

### ISSUE THREAD

**Issue by glyh** [darknessomi/musicbox#949]
复现：
1. `$ musicbox`
2. 登陆，选中某一歌单
3. Shift+C来缓存歌单

出现以下错误信息：
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/NEMbox/__main__.py", line 35, in start
    nembox_menu.start_fork(version)
  File "/usr/lib/python3.10/site-packages/NEMbox/menu.py", line 293, in start_fork
    Menu().start()
  File "/usr/lib/python3.10/site-packages/NEMbox/menu.py", line 951, in start
    args=(s["song_id"], s["song_name"], s["artist"], s["mp3_url"]),
KeyError: 'song_id'
```

**Comment by LuoShaoyin** [comment]
同样遇到问题， Ubuntu 22.04, python 3.10

**Comment by darknessomi** [comment]
已在 #972 中修复。

**原因：** 在歌单列表（非歌曲视图）按 Shift+C 缓存时，代码直接访问 `song_id` 字段，导致 `KeyError: 'song_id'`。

**修复：** 缓存前校验 `datatype` 为歌曲类型且当前项包含 `song_id`，否则跳过。

请更新到最新 master 后验证。
