### ISSUE TITLE
树莓派报错

### ISSUE THREAD

**Issue by hy4015** [darknessomi/musicbox#950]
Traceback (most recent call last):
  File "/usr/local/bin/musicbox", line 6, in <module>
    from NEMbox.__main__ import start
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/__main__.py", line 16, in <module>
    from .menu import Menu
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/menu.py", line 24, in <module>
    from .api import NetEase
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/api.py", line 20, in <module>
    import requests_cache
  File "/usr/local/lib/python2.7/dist-packages/requests_cache/__init__.py", line 6, in <module>
    from .response import AnyResponse, CachedHTTPResponse, CachedResponse, ExpirationTime
  File "/usr/local/lib/python2.7/dist-packages/requests_cache/response.py", line 39
    def __init__(self, original_response: Response, expire_after: ExpirationTime = None):
                                        ^
SyntaxError: invalid syntax

**Comment by kigawas** [comment]
需要安装到Python3

**Comment by hy4015** [comment]
Hi 请问下如何安装到Python3 呀，谢谢~
&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "darknessomi/musicbox"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月9日(星期一) 下午2:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [darknessomi/musicbox] 树莓派报错 (Issue #950)





 
需要安装到Python3

**Comment by hy4015** [comment]
搞定了，谢谢！




&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "darknessomi/musicbox"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月9日(星期一) 下午2:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [darknessomi/musicbox] 树莓派报错 (Issue #950)





 
Closed #950.
