### ISSUE TITLE
树莓派登入账户时报错

### ISSUE THREAD

**Issue by hy4015** [darknessomi/musicbox#952]
Traceback (most recent call last):
File "/usr/local/bin/musicbox", line 10, in <module>
sys.exit(start())
File "/usr/local/lib/python3.7/dist-packages/NEMbox/__main__.py", line 35, in start
nembox_menu.start_fork(version)
File "/usr/local/lib/python3.7/dist-packages/NEMbox/menu.py", line 293, in start_fork
Menu().start()
File "/usr/local/lib/python3.7/dist-packages/NEMbox/menu.py", line 709, in start
self.enter_page_event()
File "/usr/local/lib/python3.7/dist-packages/NEMbox/menu.py", line 428, in enter_page_event
self.dispatch_enter(idx)
File "/usr/local/lib/python3.7/dist-packages/NEMbox/menu.py", line 991, in dispatch_enter
self.choice_channel(idx)
File "/usr/local/lib/python3.7/dist-packages/NEMbox/menu.py", line 1218, in choice_channel
self.login()
File "/usr/local/lib/python3.7/dist-packages/NEMbox/menu.py", line 188, in login
resp = self.api.login(account, md5pass)
File "/usr/local/lib/python3.7/dist-packages/NEMbox/api.py", line 393, in login
self.session.cookies.save()
File "/usr/lib/python3.7/http/cookiejar.py", line 1890, in save
f.write(self.as_lwp_str(ignore_discard, ignore_expires))
File "/usr/lib/python3.7/http/cookiejar.py", line 1877, in as_lwp_str
r.append("Set-Cookie3: %s" % lwp_cookie_str(cookie))
File "/usr/lib/python3.7/http/cookiejar.py", line 1838, in lwp_cookie_str
time2isoz(float(cookie.expires))))
File "/usr/lib/python3.7/http/cookiejar.py", line 101, in time2isoz
dt = datetime.datetime.utcfromtimestamp(t)
OverflowError: timestamp out of range for platform time_t

**Comment by kigawas** [comment]
可以试一下master能不能用

**Comment by hy4015** [comment]
请问master指的是？我比较小白。。&nbsp;

过去不等于未来!!


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Weiliang ***@***.***&gt;; 
发送时间: 2022年5月11日(星期三) 下午4:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [darknessomi/musicbox] 树莓派登入账户时报错 (Issue #952)





 
可以试一下master能不能用

**Comment by fussun** [comment]
> 请问master指的是？我比较小白。。&nbsp; 过去不等于未来!! &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Weiliang ***@***.***&gt;; 发送时间: 2022年5月11日(星期三) 下午4:27 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [darknessomi/musicbox] 树莓派登入账户时报错 (Issue #952) 可以试一下master能不能用 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

Git clone 安装 master 分支（*nix 系统）
    git clone https://github.com/darknessomi/musicbox.git && cd musicbox
    poetry build && poetry install

小白有点难了

**Comment by darknessomi** [comment]
该问题根因是 32 位系统上 LWPCookieJar 保存 cookie 时 `OverflowError: timestamp out of range for platform time_t`。

已在 #941 中修复：改用 `MozillaCookieJar` 替代 `LWPCookieJar`，当前 master 分支 `NEMbox/api.py` 已使用该实现。此外登录流程已改为扫码登录，不再走旧版账号密码登录路径。

如仍有问题请 reopen 并注明 Python 版本与安装方式。
