### ISSUE TITLE
我在排行榜音乐里面搜索伍佰的歌曲，出现报错

### ISSUE THREAD

**Issue by LinuxProgramDevelop** [darknessomi/musicbox#961]
tee@ts7-Pro Big_Txt_To_ELK_data % musicbox
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/NEMbox/__main__.py", line 35, in start
    nembox_menu.start_fork(version)
  File "/usr/local/lib/python3.9/site-packages/NEMbox/menu.py", line 293, in start_fork
    Menu().start()
  File "/usr/local/lib/python3.9/site-packages/NEMbox/menu.py", line 722, in start
    self.datalist, keyword = self.in_place_search()
  File "/usr/local/lib/python3.9/site-packages/NEMbox/menu.py", line 211, in in_place_search
    item["origin_index"] = origin_index
TypeError: 'str' object does not support item assignment

**Comment by LinuxProgramDevelop** [comment]
trainee@traineedeWindows7-Pro Big_Txt_To_ELK_data % musicbox
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/NEMbox/__main__.py", line 35, in start
    nembox_menu.start_fork(version)
  File "/usr/local/lib/python3.9/site-packages/NEMbox/menu.py", line 293, in start_fork
    Menu().start()
  File "/usr/local/lib/python3.9/site-packages/NEMbox/menu.py", line 722, in start
    self.datalist, keyword = self.in_place_search()
  File "/usr/local/lib/python3.9/site-packages/NEMbox/menu.py", line 211, in in_place_search
    item["origin_index"] = origin_index
TypeError: 'str' object does not support item assignment

**Comment by darknessomi** [comment]
已在 #972 中修复。

**原因：** 模糊搜索 `in_place_search()` 对排行榜等字符串列表项直接写入 `origin_index`，触发 `TypeError: 'str' object does not support item assignment`；歌曲 dict 也未匹配 `song_name`/`artist` 等字段。

**修复：** 字符串项包装为带 `_search_label` 的 dict，歌曲字段纳入搜索文本，并补充单元测试。

请更新到最新 master 后验证。
